// apps/web-svelte/src/routes/chat/+page.svelte
<script lang="ts">
  import type { PageData } from './$types';
  import { base } from '$app/paths';
  import { MessageCircle, Plus, LogOut, Mic, StopCircle, Paperclip, Send, Settings2, ChevronRight } from 'lucide-svelte';

  let { data }: { data: PageData } = $props();

  interface Message {
    id: string;
    role: 'user' | 'assistant' | 'system';
    content: string;
    created_at: string;
    model_used?: string | null;
    metadata?: {
      agent?: string;
      reasoning_mode?: string;
      reasoning_label?: string;
      visible_reasoning_summary?: string[];
      source_trace?: string[];
    } | null;
  }

  interface Conversation {
    id: string;
    title: string | null;
    zone: string;
    created_at: string;
    updated_at: string;
  }

  type Zone = 'PUBLIC' | 'WORKSPACE' | 'FAMILY_PRIVATE';

  const ZONE_LABELS: Record<Zone, string> = {
    PUBLIC: '🌍 Public',
    WORKSPACE: '💼 Workspace',
    FAMILY_PRIVATE: '👨‍👩‍👦 Family',
  };

  const ZONE_COLORS: Record<Zone, string> = {
    PUBLIC: 'bg-green-500/20 text-green-300 border-green-500/30',
    WORKSPACE: 'bg-blue-500/20 text-blue-300 border-blue-500/30',
    FAMILY_PRIVATE: 'bg-purple-500/20 text-purple-300 border-purple-500/30',
  };

  let conversations = $state<Conversation[]>([]);
  let activeConversation = $state<Conversation | null>(null);
  let messages = $state<Message[]>([]);
  let input = $state('');
  let loading = $state(false);
  let sidebarOpen = $state(false);
  let selectedZone = $state<Zone>('FAMILY_PRIVATE');
  let availableZones = $state<Zone[]>(['WORKSPACE', 'FAMILY_PRIVATE', 'PUBLIC']);
  let runtimeOptions = $state({ available_models: [] as string[], default_model: 'llama3.1:8b', agent_options: [] as {id:string,label:string}[], reasoning_modes: [] as {id:string,label:string}[], source_modes: [] as {id:string,label:string}[], voice: { available: false } });
  let selectedModel = $state('');
  let selectedAgent = $state('kirobi');
  let reasoningMode = $state('normal');
  let sourceModes = $state<string[]>(['local']);
  let showReasoning = $state(true);
  let settingsOpen = $state(false);
  let recording = $state(false);
  let transcribing = $state(false);
  let messagesEnd: HTMLDivElement | undefined = $state();

  let mediaRecorder: MediaRecorder | null = null;
  let mediaStream: MediaStream | null = null;
  let audioChunks: Blob[] = [];

  const token = $derived(data.session);

  async function apiFetch(path: string, options: RequestInit = {}) {
    const res = await fetch(`/api${path}`, {
      ...options,
      headers: { 'Authorization': `Bearer ${token}`, 'Content-Type': 'application/json', ...(options.headers ?? {}) },
    });
    if (!res.ok) throw new Error(`API ${res.status}`);
    return res.json();
  }

  async function init() {
    try {
      const [perms, convs, rt] = await Promise.all([
        apiFetch('/auth/me/permissions'),
        apiFetch('/conversations'),
        apiFetch('/chat/runtime/options'),
      ]);
      const writable = (perms.zones ?? []).filter((z: {zone: string, can_write: boolean}) => z.can_write && ZONE_LABELS[z.zone as Zone]).map((z: {zone: Zone}) => z.zone as Zone);
      if (writable.length > 0) availableZones = writable;
      conversations = convs;
      runtimeOptions = rt;
      selectedModel = rt.default_model || '';
      if (convs.length > 0) await selectConversation(convs[0]);
    } catch (e) { console.error(e); }
  }

  async function selectConversation(conv: Conversation) {
    activeConversation = conv;
    sidebarOpen = false;
    try {
      messages = await apiFetch(`/conversations/${conv.id}/messages`);
      setTimeout(() => messagesEnd?.scrollIntoView({ behavior: 'smooth' }), 50);
    } catch (e) { console.error(e); }
  }

  async function createNew() {
    try {
      const conv = await apiFetch('/conversations', {
        method: 'POST',
        body: JSON.stringify({ title: `${ZONE_LABELS[selectedZone]} Gespräch`, zone: selectedZone }),
      });
      conversations = [conv, ...conversations];
      activeConversation = conv;
      messages = [];
      sidebarOpen = false;
    } catch (e) { console.error(e); }
  }

  async function sendMessage(e: Event) {
    e.preventDefault();
    if (!input.trim() || !activeConversation || loading) return;
    const content = input;
    input = '';
    loading = true;
    messages = [...messages, { id: 'tmp-' + Date.now(), role: 'user', content, created_at: new Date().toISOString() }];
    setTimeout(() => messagesEnd?.scrollIntoView({ behavior: 'smooth' }), 50);
    try {
      await apiFetch(`/conversations/${activeConversation.id}/messages`, {
        method: 'POST',
        body: JSON.stringify({ content, model: selectedModel || undefined, agent: selectedAgent, reasoning_mode: reasoningMode, source_modes: sourceModes, show_reasoning: showReasoning }),
      });
      messages = await apiFetch(`/conversations/${activeConversation.id}/messages`);
    } catch (e) { console.error(e); }
    finally { loading = false; setTimeout(() => messagesEnd?.scrollIntoView({ behavior: 'smooth' }), 100); }
  }

  async function toggleVoice() {
    if (recording && mediaRecorder) {
      mediaRecorder.stop();
      recording = false;
      return;
    }
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
      mediaStream = stream;
      audioChunks = [];
      const mr = new MediaRecorder(stream);
      mediaRecorder = mr;
      mr.ondataavailable = (e) => { if (e.data.size > 0) audioChunks.push(e.data); };
      mr.onstop = async () => {
        transcribing = true;
        try {
          const blob = new Blob(audioChunks, { type: mr.mimeType || 'audio/webm' });
          const fd = new FormData();
          fd.append('audio_file', blob, 'voice.webm');
          fd.append('language', 'de');
          const res = await fetch('/voice/stt/transcribe', { method: 'POST', headers: { 'Authorization': `Bearer ${token}` }, body: fd });
          if (res.ok) {
            const p = await res.json();
            const t = p.text || p.transcription || '';
            if (t) input = input ? `${input} ${t}` : t;
          }
        } finally {
          mediaStream?.getTracks().forEach(t => t.stop());
          mediaStream = null; audioChunks = []; transcribing = false; recording = false;
        }
      };
      mr.start();
      recording = true;
    } catch { alert('Mikrofonzugriff nicht verfügbar'); }
  }

  $effect(() => { init(); });
  $effect(() => { return () => { mediaStream?.getTracks().forEach(t => t.stop()); }; });
</script>

<svelte:head><title>Chat · Kirobi</title></svelte:head>

<div class="flex h-[calc(100vh-3.5rem)] md:h-[calc(100vh-3.5rem)] bg-gray-950 text-white overflow-hidden">
  <!-- Sidebar -->
  <div class="
    {sidebarOpen ? 'translate-x-0' : '-translate-x-full'} md:translate-x-0
    fixed md:static inset-y-0 left-0 z-50 w-64
    bg-gray-900 border-r border-white/10
    transition-transform duration-300 flex flex-col
  ">
    <div class="p-4 border-b border-white/10 space-y-3">
      <p class="font-semibold text-sm">{data.user?.display_name ?? 'Kirobi'}</p>
      <button onclick={createNew} class="w-full flex items-center justify-center gap-2 px-3 py-2 bg-aurora-cyan/15 hover:bg-aurora-cyan/25 text-aurora-cyan rounded-lg text-sm transition-colors">
        <Plus class="w-4 h-4" /> Neues Gespräch
      </button>
      <div class="flex flex-wrap gap-1.5">
        {#each availableZones as zone}
          <button onclick={() => selectedZone = zone} class="rounded-full border px-2 py-0.5 text-xs transition-colors {selectedZone === zone ? ZONE_COLORS[zone] : 'border-white/10 text-gray-400'}">
            {ZONE_LABELS[zone]}
          </button>
        {/each}
      </div>
    </div>
    <div class="flex-1 overflow-y-auto p-2">
      {#each conversations as conv}
        <button onclick={() => selectConversation(conv)} class="w-full text-left px-3 py-2 rounded-lg mb-1 transition-colors {activeConversation?.id === conv.id ? 'bg-aurora-cyan/15 text-aurora-cyan' : 'hover:bg-white/5 text-gray-300'}">
          <div class="flex items-center gap-2">
            <MessageCircle class="w-4 h-4 flex-shrink-0" />
            <span class="truncate text-sm">{conv.title || 'Gespräch'}</span>
          </div>
          <p class="text-xs text-gray-500 mt-0.5">{new Date(conv.updated_at).toLocaleDateString('de-DE')} · {conv.zone}</p>
        </button>
      {/each}
    </div>
    <div class="p-4 border-t border-white/10">
      <a href="{base}/login" class="w-full flex items-center justify-center gap-2 px-3 py-2 bg-red-600/20 hover:bg-red-600/30 text-red-300 rounded-lg text-sm transition-colors">
        <LogOut class="w-4 h-4" /> Abmelden
      </a>
    </div>
  </div>

  <!-- Chat area -->
  <div class="flex-1 flex flex-col min-w-0">
    <!-- Header -->
    <div class="border-b border-white/10 bg-gray-900/50 px-4 py-2 flex items-center gap-2">
      <button onclick={() => sidebarOpen = !sidebarOpen} class="md:hidden text-gray-400 hover:text-white p-1">
        <MessageCircle class="w-5 h-5" />
      </button>
      {#if activeConversation}
        <span class="rounded-full border px-2 py-0.5 text-xs {ZONE_COLORS[activeConversation.zone as Zone] ?? 'border-white/10 text-gray-300'}">
          {ZONE_LABELS[activeConversation.zone as Zone] ?? activeConversation.zone}
        </span>
        <span class="text-xs text-gray-400">{selectedModel || runtimeOptions.default_model}</span>
        <span class="text-xs text-gray-500">{runtimeOptions.agent_options.find(a => a.id === selectedAgent)?.label ?? selectedAgent}</span>
      {/if}
      <button onclick={() => settingsOpen = !settingsOpen} class="ml-auto flex items-center gap-1 px-2 py-1 rounded-lg border text-xs transition-colors {settingsOpen ? 'border-aurora-cyan/40 text-aurora-cyan' : 'border-white/10 text-gray-400 hover:text-white'}">
        <Settings2 class="w-3.5 h-3.5" />
      </button>
    </div>

    {#if settingsOpen}
      <div class="border-b border-white/10 bg-gray-900 px-4 py-3 grid grid-cols-2 md:grid-cols-4 gap-3">
        <label class="space-y-1">
          <span class="text-[10px] uppercase tracking-wider text-gray-500">Agent</span>
          <select bind:value={selectedAgent} class="w-full rounded-lg border border-white/10 bg-gray-950 px-2 py-1.5 text-xs text-white">
            {#each runtimeOptions.agent_options as a}<option value={a.id}>{a.label}</option>{/each}
          </select>
        </label>
        <label class="space-y-1">
          <span class="text-[10px] uppercase tracking-wider text-gray-500">Modell</span>
          <select bind:value={selectedModel} class="w-full rounded-lg border border-white/10 bg-gray-950 px-2 py-1.5 text-xs text-white">
            {#each (runtimeOptions.available_models.length > 0 ? runtimeOptions.available_models : [runtimeOptions.default_model]) as m}<option value={m}>{m}</option>{/each}
          </select>
        </label>
        <div class="space-y-1">
          <span class="text-[10px] uppercase tracking-wider text-gray-500">Denkgrad</span>
          <div class="flex flex-wrap gap-1">
            {#each runtimeOptions.reasoning_modes as mode}
              <button onclick={() => reasoningMode = mode.id} class="px-2 py-1 rounded border text-[10px] transition-colors {reasoningMode === mode.id ? 'border-aurora-violet/60 bg-aurora-violet/15 text-aurora-violet' : 'border-white/10 text-gray-400'}">{mode.label}</button>
            {/each}
          </div>
        </div>
        <label class="flex items-center gap-2 text-xs text-gray-300">
          <input type="checkbox" bind:checked={showReasoning} class="rounded border-white/20" />
          Reasoning anzeigen
        </label>
      </div>
    {/if}

    <!-- Messages -->
    <div class="flex-1 overflow-y-auto p-4 space-y-3">
      {#if !activeConversation}
        <div class="h-full flex items-center justify-center text-gray-500">
          <div class="text-center">
            <MessageCircle class="w-12 h-12 mx-auto mb-3 opacity-30" />
            <p>Wähle ein Gespräch oder starte ein neues</p>
          </div>
        </div>
      {:else if messages.length === 0}
        <div class="h-full flex items-center justify-center text-gray-500">
          <div class="text-center">
            <p class="text-lg mb-2">Hallo {data.user?.display_name ?? ''}! 👋</p>
            <p class="text-sm">Wie kann ich dir helfen?</p>
          </div>
        </div>
      {:else}
        {#each messages as msg}
          <div class="flex {msg.role === 'user' ? 'justify-end' : 'justify-start'}">
            <div class="max-w-[80%] p-3 rounded-2xl text-sm {msg.role === 'user' ? 'bg-aurora-cyan/20 text-white' : 'bg-white/5 text-gray-100'}">
              <p class="whitespace-pre-wrap">{msg.content}</p>
              {#if msg.role === 'assistant' && msg.metadata?.visible_reasoning_summary?.length && showReasoning}
                <div class="mt-2 pt-2 border-t border-white/10 space-y-1">
                  {#each msg.metadata.visible_reasoning_summary as s}
                    <p class="text-[10px] text-gray-400">• {s}</p>
                  {/each}
                </div>
              {/if}
              <p class="text-[10px] text-gray-500 mt-1.5">{new Date(msg.created_at).toLocaleTimeString('de-DE', { hour: '2-digit', minute: '2-digit' })}</p>
            </div>
          </div>
        {/each}
        {#if loading}
          <div class="flex justify-start">
            <div class="bg-white/5 p-3 rounded-2xl">
              <div class="flex gap-1">
                <div class="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style="animation-delay:0ms"></div>
                <div class="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style="animation-delay:150ms"></div>
                <div class="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style="animation-delay:300ms"></div>
              </div>
            </div>
          </div>
        {/if}
        <div bind:this={messagesEnd}></div>
      {/if}
    </div>

    <!-- Input -->
    {#if activeConversation}
      <div class="border-t border-white/10 p-3">
        <form onsubmit={sendMessage} class="flex items-end gap-2">
          <button type="button" onclick={toggleVoice} disabled={transcribing} class="flex-shrink-0 p-2.5 rounded-xl transition-colors disabled:opacity-50 {recording ? 'bg-red-600 hover:bg-red-700' : 'bg-white/5 hover:bg-white/10'}">
            {#if recording}<StopCircle class="w-5 h-5" />{:else}<Mic class="w-5 h-5" />{/if}
          </button>
          <textarea
            bind:value={input}
            onkeydown={(e) => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); sendMessage(e); } }}
            placeholder={transcribing ? 'Transkribiere...' : 'Schreibe eine Nachricht…'}
            disabled={loading || transcribing}
            rows={1}
            class="flex-1 bg-white/5 border border-white/10 rounded-xl px-3 py-2.5 text-sm text-white resize-none focus:outline-none focus:border-aurora-cyan/40 placeholder-gray-600"
          ></textarea>
          <button type="submit" disabled={loading || !input.trim()} class="flex-shrink-0 p-2.5 bg-aurora-cyan/20 hover:bg-aurora-cyan/30 text-aurora-cyan rounded-xl transition-colors disabled:opacity-30">
            <Send class="w-5 h-5" />
          </button>
        </form>
      </div>
    {/if}
  </div>

  {#if sidebarOpen}
    <button onclick={() => sidebarOpen = false} class="md:hidden fixed inset-0 bg-black/60 z-40" aria-label="Sidebar schließen"></button>
  {/if}
</div>

// apps/portal/src/app/chat/page.tsx
'use client';

import { formatDistanceToNow } from 'date-fns';
import { de } from 'date-fns/locale';
import { motion } from 'framer-motion';
import {
  Menu,
  Mic,
  Paperclip,
  Plus,
  Search,
  SendHorizontal,
  X,
} from 'lucide-react';
import { useRouter, useSearchParams } from 'next/navigation';
import { Suspense, useEffect, useMemo, useRef, useState } from 'react';

import { AgentAvatar } from '@/components/chat/AgentAvatar';
import { ChatBubble } from '@/components/chat/ChatBubble';
import { BottomNav } from '@/components/layout/BottomNav';
import { Header } from '@/components/layout/Header';
import { useRequireAuth } from '@/lib/auth';
import {
  createConversation,
  sendMessage,
  uploadFile,
  useConversations,
  useMessages,
  type AttachmentReference,
  type Message,
} from '@/lib/api';

function ChatPageContent() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const { isLoading, isAuthenticated } = useRequireAuth();
  const { data: conversations = [], mutate: mutateConversations } = useConversations();
  const activeConversationId = searchParams.get('conversation') ?? conversations[0]?.id ?? null;
  const { data: messages = [], mutate: mutateMessages } = useMessages(activeConversationId);

  const [search, setSearch] = useState('');
  const [composer, setComposer] = useState('');
  const [mobileSidebarOpen, setMobileSidebarOpen] = useState(false);
  const [pendingAttachments, setPendingAttachments] = useState<AttachmentReference[]>([]);
  const [isSending, setIsSending] = useState(false);

  const fileInputRef = useRef<HTMLInputElement | null>(null);
  const messagesEndRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    if (!activeConversationId && conversations.length > 0) {
      router.replace(`/chat?conversation=${conversations[0].id}`);
    }
  }, [activeConversationId, conversations, router]);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, isSending]);

  const filteredConversations = useMemo(() => {
    const term = search.trim().toLowerCase();
    if (!term) {
      return conversations;
    }
    return conversations.filter((conversation) => conversation.title.toLowerCase().includes(term));
  }, [conversations, search]);

  const handleCreateConversation = async () => {
    const conversation = await createConversation(`Neuer Chat · ${new Date().toLocaleTimeString('de-DE', { hour: '2-digit', minute: '2-digit' })}`, 'WORKSPACE');
    await mutateConversations((current = []) => [conversation, ...current], false);
    router.push(`/chat?conversation=${conversation.id}`);
    setMobileSidebarOpen(false);
    return conversation;
  };

  const handleAttachFile = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const selectedFile = event.target.files?.[0];
    if (!selectedFile) {
      return;
    }

    const uploaded = await uploadFile(selectedFile, 'WORKSPACE');
    const attachment: AttachmentReference = {
      id: String(uploaded.id ?? uploaded.fileId ?? selectedFile.name),
      name: String(uploaded.name ?? selectedFile.name),
      url: uploaded.url ? String(uploaded.url) : undefined,
      path: uploaded.path ? String(uploaded.path) : undefined,
      zone: 'WORKSPACE',
    };

    setPendingAttachments((current) => [...current, attachment]);
    setComposer((current) => `${current}${current ? '\n' : ''}[Anhang: ${attachment.name}]`);
    event.target.value = '';
  };

  const handleSend = async () => {
    const content = composer.trim();

    if (!content && pendingAttachments.length === 0) {
      return;
    }

    setIsSending(true);

    try {
      const targetConversation = activeConversationId
        ? { id: activeConversationId }
        : await handleCreateConversation();

      const optimisticMessage: Message = {
        id: `optimistic-${Date.now()}`,
        role: 'user',
        content,
        createdAt: new Date().toISOString(),
        attachments: pendingAttachments,
      };

      setComposer('');
      setPendingAttachments([]);

      if (targetConversation.id === activeConversationId) {
        await mutateMessages((current = []) => [...current, optimisticMessage], false);
      }

      const result = await sendMessage(targetConversation.id, content, pendingAttachments);

      if (targetConversation.id === activeConversationId) {
        await mutateMessages(
          (current = []) => {
            const withoutOptimistic = current.filter((message) => message.id !== optimisticMessage.id);
            return [
              ...withoutOptimistic,
              result.userMessage,
              ...(result.assistantMessage ? [result.assistantMessage] : []),
            ];
          },
          false,
        );
      } else {
        router.replace(`/chat?conversation=${targetConversation.id}`);
      }

      await mutateConversations();
    } finally {
      setIsSending(false);
    }
  };

  if (isLoading || !isAuthenticated) {
    return <div className="min-h-screen bg-void" />;
  }

  return (
    <div className="min-h-screen pb-24 md:pb-0">
      <Header title="Chat" />
      <main className="flex min-h-screen pt-14">
        <aside
          className={`fixed inset-y-14 left-0 z-30 w-[88vw] max-w-sm border-r border-white/10 bg-void-deep/95 p-4 backdrop-blur-xl transition md:static md:w-80 md:translate-x-0 ${
            mobileSidebarOpen ? 'translate-x-0' : '-translate-x-full'
          }`}
        >
          <div className="mb-4 flex items-center justify-between md:hidden">
            <h2 className="text-lg font-semibold">Gespräche</h2>
            <button type="button" onClick={() => setMobileSidebarOpen(false)} className="rounded-full border border-white/10 p-2">
              <X className="h-4 w-4" />
            </button>
          </div>
          <button
            type="button"
            onClick={() => void handleCreateConversation()}
            className="mb-4 flex w-full items-center justify-center gap-2 rounded-2xl bg-gradient-to-r from-kirobi-400 to-aurora-violet px-4 py-3 font-semibold text-void shadow-glow-cyan"
          >
            <Plus className="h-4 w-4" />
            Neuer Chat
          </button>
          <div className="relative mb-4">
            <Search className="pointer-events-none absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-white/35" />
            <input
              value={search}
              onChange={(event) => setSearch(event.target.value)}
              placeholder="Gespräche suchen"
              className="h-11 w-full rounded-2xl border border-white/10 bg-white/5 pl-11 pr-4 text-sm outline-none focus:border-aurora-cyan/40"
            />
          </div>
          <div className="space-y-3 overflow-y-auto pb-10">
            {filteredConversations.map((conversation) => {
              const active = conversation.id === activeConversationId;

              return (
                <button
                  key={conversation.id}
                  type="button"
                  onClick={() => {
                    router.push(`/chat?conversation=${conversation.id}`);
                    setMobileSidebarOpen(false);
                  }}
                  className={`w-full rounded-3xl border p-4 text-left transition ${
                    active
                      ? 'border-aurora-cyan/35 bg-white/10 shadow-glow-cyan'
                      : 'border-white/10 bg-white/5 hover:bg-white/10'
                  }`}
                >
                  <div className="flex items-start gap-3">
                    <AgentAvatar name={conversation.agent} size="sm" />
                    <div className="min-w-0 flex-1">
                      <div className="truncate font-medium text-white">{conversation.title}</div>
                      <div className="mt-1 text-xs text-white/45">
                        {formatDistanceToNow(new Date(conversation.updatedAt), { addSuffix: true, locale: de })}
                      </div>
                    </div>
                    <span className="rounded-full border border-white/10 px-2 py-1 text-[10px] uppercase tracking-[0.2em] text-white/45">
                      {conversation.agent}
                    </span>
                  </div>
                </button>
              );
            })}
          </div>
        </aside>

        <div className="flex min-w-0 flex-1 flex-col bg-void px-4 pb-20 pt-4 md:px-6">
          <div className="mb-4 flex items-center justify-between gap-3 md:hidden">
            <button
              type="button"
              onClick={() => setMobileSidebarOpen(true)}
              className="inline-flex h-11 w-11 items-center justify-center rounded-2xl border border-white/10 bg-white/5"
            >
              <Menu className="h-5 w-5" />
            </button>
            <button
              type="button"
              onClick={() => router.push(activeConversationId ? `/voice?conversation=${activeConversationId}` : '/voice')}
              className="inline-flex h-11 items-center gap-2 rounded-2xl border border-white/10 bg-white/5 px-4 text-sm text-white/75"
            >
              <Mic className="h-4 w-4" />
              Voice
            </button>
          </div>

          <motion.div initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} className="flex-1 overflow-y-auto">
            <div className="mx-auto flex max-w-4xl flex-col gap-5 py-6">
              {messages.length > 0 ? (
                messages.map((message) => (
                  <ChatBubble
                    key={message.id}
                    role={message.role === 'user' ? 'user' : 'assistant'}
                    content={message.content}
                    timestamp={new Date(message.createdAt)}
                    agentName={message.agentName ?? 'kirobi'}
                    modelUsed={message.modelUsed}
                  />
                ))
              ) : (
                <div className="rounded-[2rem] border border-dashed border-white/10 bg-white/5 p-8 text-center text-white/55">
                  Starte eine Unterhaltung. Kirobi wartet bereits auf deinen ersten Gedanken.
                </div>
              )}

              {isSending ? (
                <div className="flex items-center gap-3 rounded-3xl border border-white/10 bg-white/5 px-4 py-3 text-sm text-white/60">
                  <AgentAvatar name="kirobi" size="sm" />
                  <div className="flex items-center gap-1">
                    <span className="h-2 w-2 rounded-full bg-aurora-cyan animate-bounce" />
                    <span className="h-2 w-2 rounded-full bg-aurora-cyan animate-bounce [animation-delay:0.15s]" />
                    <span className="h-2 w-2 rounded-full bg-aurora-cyan animate-bounce [animation-delay:0.3s]" />
                  </div>
                  <span>Kirobi denkt gerade nach...</span>
                </div>
              ) : null}
              <div ref={messagesEndRef} />
            </div>
          </motion.div>

          <div className="sticky bottom-16 mt-4 md:bottom-4">
            <div className="mx-auto max-w-4xl rounded-[2rem] border border-white/10 bg-void-deep/90 p-4 shadow-card backdrop-blur-xl">
              {pendingAttachments.length > 0 ? (
                <div className="mb-3 flex flex-wrap gap-2">
                  {pendingAttachments.map((attachment) => (
                    <span key={attachment.id ?? attachment.name} className="rounded-full border border-aurora-cyan/20 bg-aurora-cyan/10 px-3 py-1 text-xs text-aurora-cyan">
                      {attachment.name}
                    </span>
                  ))}
                </div>
              ) : null}
              <div className="flex items-end gap-3">
                <button
                  type="button"
                  onClick={() => fileInputRef.current?.click()}
                  className="inline-flex h-11 w-11 items-center justify-center rounded-2xl border border-white/10 bg-white/5 text-white/70 transition hover:text-white"
                >
                  <Paperclip className="h-5 w-5" />
                </button>
                <textarea
                  value={composer}
                  onChange={(event) => setComposer(event.target.value)}
                  onKeyDown={(event) => {
                    if (event.key === 'Enter' && !event.shiftKey) {
                      event.preventDefault();
                      void handleSend();
                    }
                  }}
                  placeholder="Schreib Kirobi, was dich gerade bewegt..."
                  className="min-h-[60px] flex-1 resize-none rounded-3xl border border-white/10 bg-white/5 px-4 py-4 text-sm outline-none focus:border-aurora-cyan/35"
                />
                <button
                  type="button"
                  onClick={() => router.push(activeConversationId ? `/voice?conversation=${activeConversationId}` : '/voice')}
                  className="hidden h-11 w-11 items-center justify-center rounded-2xl border border-white/10 bg-white/5 text-white/70 transition hover:text-white md:inline-flex"
                >
                  <Mic className="h-5 w-5" />
                </button>
                <button
                  type="button"
                  onClick={() => void handleSend()}
                  disabled={isSending}
                  className="inline-flex h-11 w-11 items-center justify-center rounded-2xl bg-gradient-to-r from-kirobi-400 to-aurora-violet text-void shadow-glow-cyan disabled:opacity-60"
                >
                  <SendHorizontal className="h-5 w-5" />
                </button>
              </div>
              <input ref={fileInputRef} type="file" className="hidden" onChange={handleAttachFile} />
            </div>
          </div>
        </div>
      </main>
      <BottomNav />
    </div>
  );
}

export default function ChatPage() {
  return (
    <Suspense fallback={<div className="min-h-screen bg-void" />}>
      <ChatPageContent />
    </Suspense>
  );
}
