// apps/web/src/app/creative/page.tsx
'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import axios from 'axios';
import {
  PhotoIcon,
  MusicalNoteIcon,
  FilmIcon,
  SparklesIcon,
  ArrowPathIcon,
} from '@heroicons/react/24/outline';

type Tab = 'image' | 'music' | 'video';

const IMG_API = '/api/image-generation';
const MUSIC_API = '/api/music-generation';
const VIDEO_API = '/api/video-generation';

interface ImageItem {
  id: string;
  prompt: string;
  model_used: string;
  zone: string;
  width: number;
  height: number;
  created_at: string;
}

interface TrackItem {
  id: string;
  prompt: string;
  enhanced_prompt?: string;
  genre?: string;
  duration_seconds: number;
  model_used: string;
  zone: string;
  is_placeholder: boolean;
  created_at: string;
}

interface VideoJob {
  id: string;
  prompt: string;
  resolution: string;
  duration_seconds: number;
  zone: string;
  status: string;
  file_path?: string | null;
  created_at: string;
  completed_at?: string | null;
  error?: string | null;
}

export default function CreativePage() {
  const router = useRouter();
  const [token, setToken] = useState('');
  const [tab, setTab] = useState<Tab>('image');

  useEffect(() => {
    const t = typeof window !== 'undefined' ? localStorage.getItem('kirobi_token') : null;
    if (!t) { router.push('/'); return; }
    setToken(t);
  }, [router]);

  if (!token) return null;

  return (
    <div className="min-h-screen bg-gradient-to-b from-gray-950 via-gray-900 to-gray-950 text-white pb-24">
      <div className="max-w-6xl mx-auto px-4 py-8">
        <header className="mb-6">
          <h1 className="text-3xl font-bold tracking-tight flex items-center gap-2">
            <SparklesIcon className="w-8 h-8 text-fuchsia-400" />
            Kreativ-Studio
          </h1>
          <p className="text-gray-400 mt-1 text-sm">
            Bilder, Musik und Videos — alles lokal auf deiner RTX 3090.
          </p>
        </header>

        <div className="flex gap-2 mb-6 border-b border-gray-800">
          <TabBtn active={tab === 'image'} onClick={() => setTab('image')} icon={PhotoIcon} label="Bild" />
          <TabBtn active={tab === 'music'} onClick={() => setTab('music')} icon={MusicalNoteIcon} label="Musik" />
          <TabBtn active={tab === 'video'} onClick={() => setTab('video')} icon={FilmIcon} label="Video" />
        </div>

        {tab === 'image' && <ImagePanel />}
        {tab === 'music' && <MusicPanel />}
        {tab === 'video' && <VideoPanel />}
      </div>
    </div>
  );
}

function TabBtn({ active, onClick, icon: Icon, label }: { active: boolean; onClick: () => void; icon: React.ComponentType<{ className?: string }>; label: string }) {
  return (
    <button
      onClick={onClick}
      className={`flex items-center gap-2 px-4 py-3 border-b-2 transition-colors ${
        active ? 'border-fuchsia-500 text-white' : 'border-transparent text-gray-400 hover:text-white hover:border-gray-700'
      }`}
    >
      <Icon className="w-5 h-5" />
      <span className="text-sm font-medium">{label}</span>
    </button>
  );
}

// ---------- Image ----------
function ImagePanel() {
  const [prompt, setPrompt] = useState('');
  const [model, setModel] = useState('llava:13b');
  const [width, setWidth] = useState(512);
  const [height, setHeight] = useState(512);
  const [zone, setZone] = useState('WORKSPACE');
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState('');
  const [items, setItems] = useState<ImageItem[]>([]);

  async function load() {
    try {
      const r = await axios.get<ImageItem[]>(`${IMG_API}/images?limit=24`);
      setItems(r.data);
    } catch (e) { console.error(e); }
  }
  useEffect(() => { load(); }, []);

  async function generate() {
    if (!prompt.trim()) return;
    setBusy(true); setErr('');
    try {
      await axios.post(`${IMG_API}/generate`, { prompt, model, width, height, zone });
      setPrompt('');
      await load();
    } catch (e: unknown) {
      const m = e instanceof Error ? e.message : String(e);
      setErr(`Fehler: ${m}`);
    } finally { setBusy(false); }
  }

  return (
    <div className="space-y-6">
      <div className="bg-gray-900/60 border border-gray-800 rounded-xl p-4">
        <textarea
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          placeholder="Beschreibe das Bild ... z.B. 'Sonnenuntergang ueber den Bergen, fotorealistisch'"
          className="w-full bg-gray-800 border border-gray-700 rounded-lg px-3 py-2 text-sm h-24 focus:outline-none focus:border-fuchsia-500 resize-none"
        />
        <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-3">
          <FieldSelect label="Modell" value={model} onChange={setModel}
            options={[['llava:13b','LLaVA 13B'],['llava:7b','LLaVA 7B'],['stable-diffusion','Stable Diffusion']]} />
          <FieldSelect label="Breite" value={String(width)} onChange={(v) => setWidth(Number(v))}
            options={[['256','256'],['512','512'],['768','768'],['1024','1024']]} />
          <FieldSelect label="Hoehe" value={String(height)} onChange={(v) => setHeight(Number(v))}
            options={[['256','256'],['512','512'],['768','768'],['1024','1024']]} />
          <FieldSelect label="Zone" value={zone} onChange={setZone}
            options={[['PUBLIC','PUBLIC'],['WORKSPACE','WORKSPACE'],['FAMILY_PRIVATE','FAMILY_PRIVATE']]} />
        </div>
        {err && <p className="text-sm text-rose-400 mt-3">{err}</p>}
        <button
          onClick={generate}
          disabled={busy || !prompt.trim()}
          className="mt-3 inline-flex items-center gap-2 px-4 py-2 bg-fuchsia-600 hover:bg-fuchsia-700 disabled:bg-gray-700 rounded-lg text-sm font-medium transition"
        >
          {busy ? <ArrowPathIcon className="w-4 h-4 animate-spin" /> : <PhotoIcon className="w-4 h-4" />}
          {busy ? 'Generiere...' : 'Bild generieren'}
        </button>
      </div>

      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
        {items.map((it) => (
          <a key={it.id} href={`${IMG_API}/file/${it.id}`} target="_blank" rel="noreferrer"
             className="group bg-gray-900/60 border border-gray-800 rounded-xl overflow-hidden hover:border-fuchsia-500 transition">
            <img src={`${IMG_API}/file/${it.id}`} alt={it.prompt} className="w-full aspect-square object-cover" />
            <div className="p-2">
              <p className="text-xs text-gray-300 line-clamp-2">{it.prompt}</p>
              <p className="text-[10px] text-gray-500 mt-1">{it.model_used} · {it.width}×{it.height}</p>
            </div>
          </a>
        ))}
        {items.length === 0 && <p className="text-gray-500 text-sm col-span-full text-center py-8">Noch keine Bilder generiert.</p>}
      </div>
    </div>
  );
}

// ---------- Music ----------
function MusicPanel() {
  const [prompt, setPrompt] = useState('');
  const [genre, setGenre] = useState('ambient');
  const [duration, setDuration] = useState(15);
  const [zone, setZone] = useState('WORKSPACE');
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState('');
  const [items, setItems] = useState<TrackItem[]>([]);

  async function load() {
    try {
      const r = await axios.get<TrackItem[]>(`${MUSIC_API}/tracks?limit=24`);
      setItems(r.data);
    } catch (e) { console.error(e); }
  }
  useEffect(() => { load(); }, []);

  async function generate() {
    if (!prompt.trim()) return;
    setBusy(true); setErr('');
    try {
      await axios.post(`${MUSIC_API}/generate`, { prompt, genre, duration_seconds: duration, zone });
      setPrompt('');
      await load();
    } catch (e: unknown) {
      const m = e instanceof Error ? e.message : String(e);
      setErr(`Fehler: ${m}`);
    } finally { setBusy(false); }
  }

  return (
    <div className="space-y-6">
      <div className="bg-gray-900/60 border border-gray-800 rounded-xl p-4">
        <textarea
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          placeholder="Beschreibe den Track ... z.B. 'entspannte Klavier-Melodie mit Regen im Hintergrund'"
          className="w-full bg-gray-800 border border-gray-700 rounded-lg px-3 py-2 text-sm h-24 focus:outline-none focus:border-fuchsia-500 resize-none"
        />
        <div className="grid grid-cols-2 md:grid-cols-3 gap-3 mt-3">
          <FieldSelect label="Genre" value={genre} onChange={setGenre}
            options={[['ambient','Ambient'],['electronic','Electronic'],['classical','Klassik'],['jazz','Jazz'],['rock','Rock'],['lofi','Lo-Fi'],['cinematic','Cinematic']]} />
          <FieldSelect label="Dauer" value={String(duration)} onChange={(v) => setDuration(Number(v))}
            options={[['10','10s'],['15','15s'],['30','30s'],['60','60s']]} />
          <FieldSelect label="Zone" value={zone} onChange={setZone}
            options={[['PUBLIC','PUBLIC'],['WORKSPACE','WORKSPACE'],['FAMILY_PRIVATE','FAMILY_PRIVATE']]} />
        </div>
        {err && <p className="text-sm text-rose-400 mt-3">{err}</p>}
        <button
          onClick={generate}
          disabled={busy || !prompt.trim()}
          className="mt-3 inline-flex items-center gap-2 px-4 py-2 bg-fuchsia-600 hover:bg-fuchsia-700 disabled:bg-gray-700 rounded-lg text-sm font-medium transition"
        >
          {busy ? <ArrowPathIcon className="w-4 h-4 animate-spin" /> : <MusicalNoteIcon className="w-4 h-4" />}
          {busy ? 'Generiere...' : 'Track generieren'}
        </button>
      </div>

      <div className="space-y-3">
        {items.map((it) => (
          <div key={it.id} className="bg-gray-900/60 border border-gray-800 rounded-xl p-4">
            <div className="flex items-start justify-between gap-3 mb-2">
              <div className="flex-1 min-w-0">
                <p className="text-sm text-gray-200 line-clamp-2">{it.prompt}</p>
                {it.enhanced_prompt && it.enhanced_prompt !== it.prompt && (
                  <p className="text-xs text-gray-500 mt-1 line-clamp-2">↳ {it.enhanced_prompt}</p>
                )}
              </div>
              <div className="text-right flex-shrink-0">
                <span className="inline-block px-2 py-0.5 bg-gray-800 rounded text-xs text-gray-300">{it.genre}</span>
                <p className="text-[10px] text-gray-500 mt-1">{it.duration_seconds}s · {it.model_used}</p>
                {it.is_placeholder && <p className="text-[10px] text-amber-400">⚠ Placeholder (AudioCraft fehlt)</p>}
              </div>
            </div>
            <audio controls src={`${MUSIC_API}/file/${it.id}`} className="w-full mt-2" />
          </div>
        ))}
        {items.length === 0 && <p className="text-gray-500 text-sm text-center py-8">Noch keine Tracks generiert.</p>}
      </div>
    </div>
  );
}

// ---------- Video ----------
function VideoPanel() {
  const [prompt, setPrompt] = useState('');
  const [resolution, setResolution] = useState('512x512');
  const [duration, setDuration] = useState(4);
  const [zone, setZone] = useState('WORKSPACE');
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState('');
  const [items, setItems] = useState<VideoJob[]>([]);

  async function load() {
    try {
      const r = await axios.get<VideoJob[]>(`${VIDEO_API}/jobs`);
      setItems(r.data);
    } catch (e) { console.error(e); }
  }
  useEffect(() => {
    load();
    const int = setInterval(load, 5000);
    return () => clearInterval(int);
  }, []);

  async function generate() {
    if (!prompt.trim()) return;
    setBusy(true); setErr('');
    try {
      await axios.post(`${VIDEO_API}/generate`, { prompt, resolution, duration, zone });
      setPrompt('');
      await load();
    } catch (e: unknown) {
      const m = e instanceof Error ? e.message : String(e);
      setErr(`Fehler: ${m}`);
    } finally { setBusy(false); }
  }

  return (
    <div className="space-y-6">
      <div className="bg-gray-900/60 border border-gray-800 rounded-xl p-4">
        <textarea
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          placeholder="Beschreibe das Video ... z.B. 'fliegender Adler ueber einer Bergkette, Sonnenaufgang'"
          className="w-full bg-gray-800 border border-gray-700 rounded-lg px-3 py-2 text-sm h-24 focus:outline-none focus:border-fuchsia-500 resize-none"
        />
        <div className="grid grid-cols-2 md:grid-cols-3 gap-3 mt-3">
          <FieldSelect label="Aufloesung" value={resolution} onChange={setResolution}
            options={[['256x256','256×256'],['512x512','512×512'],['768x768','768×768'],['1024x576','1024×576']]} />
          <FieldSelect label="Dauer" value={String(duration)} onChange={(v) => setDuration(Number(v))}
            options={[['2','2s'],['4','4s'],['8','8s'],['16','16s']]} />
          <FieldSelect label="Zone" value={zone} onChange={setZone}
            options={[['PUBLIC','PUBLIC'],['WORKSPACE','WORKSPACE'],['FAMILY_PRIVATE','FAMILY_PRIVATE']]} />
        </div>
        {err && <p className="text-sm text-rose-400 mt-3">{err}</p>}
        <button
          onClick={generate}
          disabled={busy || !prompt.trim()}
          className="mt-3 inline-flex items-center gap-2 px-4 py-2 bg-fuchsia-600 hover:bg-fuchsia-700 disabled:bg-gray-700 rounded-lg text-sm font-medium transition"
        >
          {busy ? <ArrowPathIcon className="w-4 h-4 animate-spin" /> : <FilmIcon className="w-4 h-4" />}
          {busy ? 'Job wird erstellt...' : 'Video-Job starten'}
        </button>
      </div>

      <div className="space-y-3">
        {items.map((it) => (
          <div key={it.id} className="bg-gray-900/60 border border-gray-800 rounded-xl p-4">
            <div className="flex items-start justify-between gap-3 mb-2">
              <div className="flex-1 min-w-0">
                <p className="text-sm text-gray-200 line-clamp-2">{it.prompt}</p>
                <p className="text-xs text-gray-500 mt-1">{it.resolution} · {it.duration_seconds}s · {new Date(it.created_at).toLocaleString('de-DE')}</p>
                {it.error && <p className="text-xs text-rose-400 mt-1">{it.error}</p>}
              </div>
              <span className={`flex-shrink-0 px-2 py-1 text-xs rounded ${
                it.status === 'completed' ? 'bg-emerald-900 text-emerald-300'
                : it.status === 'failed' ? 'bg-rose-900 text-rose-300'
                : it.status === 'processing' ? 'bg-amber-900 text-amber-300'
                : 'bg-gray-800 text-gray-400'
              }`}>{it.status}</span>
            </div>
            {it.status === 'completed' && (
              <video controls src={`${VIDEO_API}/file/${it.id}`} className="w-full mt-2 rounded-lg" />
            )}
          </div>
        ))}
        {items.length === 0 && <p className="text-gray-500 text-sm text-center py-8">Noch keine Videos generiert.</p>}
      </div>
    </div>
  );
}

// ---------- helpers ----------
function FieldSelect({ label, value, onChange, options }: { label: string; value: string; onChange: (v: string) => void; options: [string, string][] }) {
  return (
    <div>
      <label className="block text-xs font-medium text-gray-400 mb-1 uppercase tracking-wider">{label}</label>
      <select
        value={value}
        onChange={(e) => onChange(e.target.value)}
        className="w-full bg-gray-800 border border-gray-700 rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-fuchsia-500"
      >
        {options.map(([v, l]) => (<option key={v} value={v}>{l}</option>))}
      </select>
    </div>
  );
}

// apps/web-svelte/src/routes/creative/+page.svelte
<script lang="ts">
  import { Image, Music, Film, Sparkles, RefreshCw, Download, CheckCircle, AlertTriangle, Play } from 'lucide-svelte';

  let { data }: { data: any } = $props();
  const token = $derived(data.session);

  type Tab = 'image' | 'music' | 'video';
  let tab = $state<Tab>('image');

  // Image
  let imgPrompt = $state('');
  let imgModel = $state('sdxl-turbo');
  let imgWidth = $state(1024);
  let imgHeight = $state(1024);
  let imgLoading = $state(false);
  let imgError = $state('');
  let imgResult = $state<{id: string, url: string} | null>(null);

  // Music
  let musicPrompt = $state('');
  let musicGenre = $state('');
  let musicDuration = $state(30);
  let musicLoading = $state(false);
  let musicError = $state('');
  let musicResult = $state<{id: string, url?: string} | null>(null);

  // Video
  let videoPrompt = $state('');
  let videoRes = $state('720p');
  let videoDur = $state(5);
  let videoLoading = $state(false);
  let videoError = $state('');
  let videoResult = $state<{id: string, status: string} | null>(null);

  const h = () => ({ Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' });

  async function generateImage() {
    imgLoading = true; imgError = ''; imgResult = null;
    try {
      const r = await fetch('/api/image-generation/generate', {
        method: 'POST', headers: h(),
        body: JSON.stringify({ prompt: imgPrompt, model_id: imgModel, width: imgWidth, height: imgHeight, zone: 'WORKSPACE' })
      });
      const d = await r.json();
      if (!r.ok) throw new Error(d.detail || 'Fehler');
      imgResult = { id: d.id, url: d.url ?? `/api/image-generation/${d.id}/download` };
    } catch (e: any) { imgError = e.message; }
    finally { imgLoading = false; }
  }

  async function generateMusic() {
    musicLoading = true; musicError = ''; musicResult = null;
    try {
      const r = await fetch('/api/music-generation/generate', {
        method: 'POST', headers: h(),
        body: JSON.stringify({ prompt: musicPrompt, genre: musicGenre, duration_seconds: musicDuration, zone: 'WORKSPACE' })
      });
      const d = await r.json();
      if (!r.ok) throw new Error(d.detail || 'Fehler');
      musicResult = { id: d.id, url: d.url ?? `/api/music-generation/${d.id}/download` };
    } catch (e: any) { musicError = e.message; }
    finally { musicLoading = false; }
  }

  async function generateVideo() {
    videoLoading = true; videoError = ''; videoResult = null;
    try {
      const r = await fetch('/api/video-generation/generate', {
        method: 'POST', headers: h(),
        body: JSON.stringify({ prompt: videoPrompt, resolution: videoRes, duration_seconds: videoDur, zone: 'WORKSPACE' })
      });
      const d = await r.json();
      if (!r.ok) throw new Error(d.detail || 'Fehler');
      videoResult = { id: d.id, status: d.status };
    } catch (e: any) { videoError = e.message; }
    finally { videoLoading = false; }
  }

  const TABS: { id: Tab; label: string; icon: any }[] = [
    { id: 'image', label: 'Bild', icon: Image },
    { id: 'music', label: 'Musik', icon: Music },
    { id: 'video', label: 'Video', icon: Film },
  ];
</script>

<svelte:head><title>Creative · Kirobi</title></svelte:head>

<div class="px-4 py-6 sm:px-6 max-w-5xl mx-auto space-y-6">
  <section class="rounded-3xl border border-fuchsia-500/20 bg-gradient-to-br from-fuchsia-900/30 via-gray-900 to-gray-950 p-6">
    <span class="inline-flex items-center gap-2 rounded-full border border-fuchsia-400/20 bg-fuchsia-400/10 px-3 py-1 text-xs uppercase tracking-widest text-fuchsia-200">
      <Sparkles class="h-4 w-4" /> Creative AI
    </span>
    <h1 class="mt-4 text-3xl font-bold text-white">Generative AI Studio</h1>
    <p class="mt-2 text-sm text-gray-400">Bild · Musik · Video — alles lokal auf deiner RTX 3090.</p>
  </section>

  <!-- Tabs -->
  <div class="flex gap-2">
    {#each TABS as t}
      <button onclick={() => tab = t.id}
        class="flex items-center gap-2 rounded-xl px-4 py-2 text-sm font-medium transition-colors
               {tab === t.id ? 'bg-fuchsia-500/20 border border-fuchsia-400/30 text-fuchsia-200' : 'border border-white/10 text-gray-400 hover:text-white'}">
        <t.icon class="h-4 w-4" />{t.label}
      </button>
    {/each}
  </div>

  <!-- Image Tab -->
  {#if tab === 'image'}
    <div class="rounded-3xl border border-white/10 bg-gray-950/70 p-5 space-y-4">
      <textarea bind:value={imgPrompt} placeholder="Beschreibe das Bild..." rows={3}
        class="w-full resize-none rounded-2xl border border-white/10 bg-black/30 px-4 py-3 text-sm text-white placeholder-gray-500 focus:outline-none focus:border-fuchsia-500/50"></textarea>
      <div class="flex flex-wrap gap-3">
        <select bind:value={imgModel} class="rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-sm text-white">
          <option value="sdxl-turbo">SDXL Turbo</option>
          <option value="sdxl">SDXL</option>
          <option value="sd15">SD 1.5</option>
        </select>
        <select bind:value={imgWidth} class="rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-sm text-white">
          <option value={512}>512px</option>
          <option value={768}>768px</option>
          <option value={1024}>1024px</option>
        </select>
        <span class="self-center text-gray-500">×</span>
        <select bind:value={imgHeight} class="rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-sm text-white">
          <option value={512}>512px</option>
          <option value={768}>768px</option>
          <option value={1024}>1024px</option>
        </select>
        <button onclick={generateImage} disabled={!imgPrompt || imgLoading}
          class="ml-auto flex items-center gap-2 rounded-xl bg-fuchsia-600 px-5 py-2 text-sm font-medium text-white hover:bg-fuchsia-500 disabled:opacity-50 transition-colors">
          {#if imgLoading}<RefreshCw class="h-4 w-4 animate-spin" />{:else}<Sparkles class="h-4 w-4" />{/if}
          Generieren
        </button>
      </div>
      {#if imgError}<div class="rounded-2xl border border-red-500/30 bg-red-500/10 p-3 text-red-300 text-sm">{imgError}</div>{/if}
      {#if imgResult}
        <div class="rounded-2xl border border-fuchsia-500/20 overflow-hidden">
          <img src={imgResult.url} alt="Generated" class="w-full" />
          <div class="flex justify-end p-3">
            <a href={imgResult.url} download class="flex items-center gap-2 rounded-xl border border-white/10 px-3 py-1.5 text-sm text-gray-300 hover:text-white">
              <Download class="h-4 w-4" /> Speichern
            </a>
          </div>
        </div>
      {/if}
    </div>
  {/if}

  <!-- Music Tab -->
  {#if tab === 'music'}
    <div class="rounded-3xl border border-white/10 bg-gray-950/70 p-5 space-y-4">
      <textarea bind:value={musicPrompt} placeholder="Beschreibe den Musik-Track..." rows={3}
        class="w-full resize-none rounded-2xl border border-white/10 bg-black/30 px-4 py-3 text-sm text-white placeholder-gray-500 focus:outline-none focus:border-fuchsia-500/50"></textarea>
      <div class="flex flex-wrap gap-3">
        <input bind:value={musicGenre} placeholder="Genre (optional)" class="rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-sm text-white placeholder-gray-500 focus:outline-none" />
        <select bind:value={musicDuration} class="rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-sm text-white">
          {#each [15, 30, 60, 120] as s}<option value={s}>{s}s</option>{/each}
        </select>
        <button onclick={generateMusic} disabled={!musicPrompt || musicLoading}
          class="ml-auto flex items-center gap-2 rounded-xl bg-fuchsia-600 px-5 py-2 text-sm font-medium text-white hover:bg-fuchsia-500 disabled:opacity-50 transition-colors">
          {#if musicLoading}<RefreshCw class="h-4 w-4 animate-spin" />{:else}<Music class="h-4 w-4" />{/if}
          Komponieren
        </button>
      </div>
      {#if musicError}<div class="rounded-2xl border border-red-500/30 bg-red-500/10 p-3 text-red-300 text-sm">{musicError}</div>{/if}
      {#if musicResult?.url}
        <div class="rounded-2xl border border-fuchsia-500/20 p-4 space-y-2">
          <audio src={musicResult.url} controls class="w-full"></audio>
          <a href={musicResult.url} download class="inline-flex items-center gap-2 text-sm text-gray-400 hover:text-white">
            <Download class="h-4 w-4" /> Download
          </a>
        </div>
      {/if}
    </div>
  {/if}

  <!-- Video Tab -->
  {#if tab === 'video'}
    <div class="rounded-3xl border border-white/10 bg-gray-950/70 p-5 space-y-4">
      <textarea bind:value={videoPrompt} placeholder="Beschreibe die Video-Szene..." rows={3}
        class="w-full resize-none rounded-2xl border border-white/10 bg-black/30 px-4 py-3 text-sm text-white placeholder-gray-500 focus:outline-none focus:border-fuchsia-500/50"></textarea>
      <div class="flex flex-wrap gap-3">
        <select bind:value={videoRes} class="rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-sm text-white">
          <option value="480p">480p</option>
          <option value="720p">720p</option>
          <option value="1080p">1080p</option>
        </select>
        <select bind:value={videoDur} class="rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-sm text-white">
          {#each [3, 5, 10, 15] as s}<option value={s}>{s}s</option>{/each}
        </select>
        <button onclick={generateVideo} disabled={!videoPrompt || videoLoading}
          class="ml-auto flex items-center gap-2 rounded-xl bg-fuchsia-600 px-5 py-2 text-sm font-medium text-white hover:bg-fuchsia-500 disabled:opacity-50 transition-colors">
          {#if videoLoading}<RefreshCw class="h-4 w-4 animate-spin" />{:else}<Film class="h-4 w-4" />{/if}
          Rendern
        </button>
      </div>
      {#if videoError}<div class="rounded-2xl border border-red-500/30 bg-red-500/10 p-3 text-red-300 text-sm">{videoError}</div>{/if}
      {#if videoResult}
        <div class="rounded-2xl border border-white/10 p-4 flex items-center gap-3">
          <CheckCircle class="h-5 w-5 text-emerald-400" />
          <div>
            <p class="text-sm text-white">Job gestartet · ID: {videoResult.id}</p>
            <p class="text-xs text-gray-500">Status: {videoResult.status} — Render dauert je nach Länge mehrere Minuten.</p>
          </div>
        </div>
      {/if}
    </div>
  {/if}
</div>
