// apps/web/src/app/upload/page.tsx
'use client';

import { useEffect, useState, useRef, useCallback } from 'react';
import { useRouter } from 'next/navigation';
import axios from 'axios';
import {
  CloudArrowUpIcon,
  DocumentTextIcon,
  PhotoIcon,
  DocumentIcon,
  TrashIcon,
  ArrowDownTrayIcon,
} from '@heroicons/react/24/outline';

type Zone = 'PUBLIC' | 'WORKSPACE' | 'FAMILY_PRIVATE';

interface UploadedFile {
  id: string;
  filename: string;
  original_filename: string;
  file_size: number;
  mime_type: string;
  zone: Zone;
  created_at: string;
}

interface UploadProgress {
  filename: string;
  progress: number;
  status: 'uploading' | 'done' | 'error';
  error?: string;
}

const ZONE_LABELS: Record<Zone, string> = {
  PUBLIC: '🌍 Public',
  WORKSPACE: '💼 Workspace',
  FAMILY_PRIVATE: '👨‍👩‍👦 Family Private',
};

const ZONE_COLORS: Record<Zone, string> = {
  PUBLIC: 'bg-green-500/20 text-green-400 border-green-500/30',
  WORKSPACE: 'bg-blue-500/20 text-blue-400 border-blue-500/30',
  FAMILY_PRIVATE: 'bg-purple-500/20 text-purple-400 border-purple-500/30',
};

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

function FileTypeIcon({ mimeType }: { mimeType: string }) {
  if (mimeType.startsWith('image/')) return <PhotoIcon className="w-8 h-8 text-blue-400" />;
  if (mimeType === 'application/pdf') return <DocumentTextIcon className="w-8 h-8 text-red-400" />;
  return <DocumentIcon className="w-8 h-8 text-gray-400" />;
}

export default function UploadPage() {
  const router = useRouter();
  const [files, setFiles] = useState<UploadedFile[]>([]);
  const [selectedZone, setSelectedZone] = useState<Zone>('WORKSPACE');
  const [isDragging, setIsDragging] = useState(false);
  const [uploads, setUploads] = useState<UploadProgress[]>([]);
  const [loadingFiles, setLoadingFiles] = useState(true);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const getAxios = () =>
    axios.create({
      baseURL: '/api',
      headers: {
        Authorization: `Bearer ${localStorage.getItem('access_token') ?? ''}`,
      },
    });

  useEffect(() => {
    const token = localStorage.getItem('access_token');
    if (!token) {
      router.push('/');
      return;
    }
    loadFiles();
  }, []);

  const loadFiles = async () => {
    setLoadingFiles(true);
    try {
      const response = await getAxios().get<UploadedFile[]>('/uploads');
      setFiles(response.data);
    } catch {
      // Endpoint may not exist yet
    } finally {
      setLoadingFiles(false);
    }
  };

  const uploadFile = async (file: File) => {
    const progressEntry: UploadProgress = {
      filename: file.name,
      progress: 0,
      status: 'uploading',
    };
    setUploads((prev) => [...prev, progressEntry]);

    const formData = new FormData();
    formData.append('file', file);
    formData.append('zone', selectedZone);

    try {
      await getAxios().post('/upload', formData, {
        headers: { 'Content-Type': 'multipart/form-data' },
        onUploadProgress: (event) => {
          const percent = event.total
            ? Math.round((event.loaded * 100) / event.total)
            : 0;
          setUploads((prev) =>
            prev.map((u) =>
              u.filename === file.name ? { ...u, progress: percent } : u
            )
          );
        },
      });

      setUploads((prev) =>
        prev.map((u) =>
          u.filename === file.name ? { ...u, progress: 100, status: 'done' } : u
        )
      );
      await loadFiles();
    } catch (err: unknown) {
      const msg =
        axios.isAxiosError(err)
          ? (err.response?.data?.detail ?? 'Upload fehlgeschlagen')
          : 'Unbekannter Fehler';
      setUploads((prev) =>
        prev.map((u) =>
          u.filename === file.name ? { ...u, status: 'error', error: msg } : u
        )
      );
    }
  };

  const handleFiles = (fileList: FileList) => {
    Array.from(fileList).forEach(uploadFile);
  };

  const handleDrop = useCallback(
    (e: React.DragEvent<HTMLDivElement>) => {
      e.preventDefault();
      setIsDragging(false);
      if (e.dataTransfer.files.length > 0) {
        handleFiles(e.dataTransfer.files);
      }
    },
    [selectedZone]
  );

  const handleDragOver = (e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    setIsDragging(true);
  };

  const handleDragLeave = () => setIsDragging(false);

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files.length > 0) {
      handleFiles(e.target.files);
    }
  };

  const clearDoneUploads = () => {
    setUploads((prev) => prev.filter((u) => u.status === 'uploading'));
  };

  return (
    <div className="min-h-screen bg-gray-900 text-white">
      {/* Header */}
      <header className="bg-gray-800 border-b border-gray-700 px-4 py-4">
        <div className="max-w-3xl mx-auto flex items-center space-x-3">
          <button
            onClick={() => router.push('/chat')}
            className="text-gray-400 hover:text-white transition-colors text-sm"
          >
            ← Zurück
          </button>
          <h1 className="text-xl font-bold">Datei-Upload</h1>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-4 py-8 space-y-6">
        {/* Zone Selector */}
        <section className="bg-gray-800 rounded-xl p-6 border border-gray-700">
          <h2 className="text-sm font-medium text-gray-400 mb-3">Zone auswählen</h2>
          <div className="flex flex-wrap gap-2">
            {(Object.keys(ZONE_LABELS) as Zone[]).map((zone) => (
              <button
                key={zone}
                onClick={() => setSelectedZone(zone)}
                className={`px-4 py-2 rounded-lg border text-sm font-medium transition-colors ${
                  selectedZone === zone
                    ? ZONE_COLORS[zone]
                    : 'bg-gray-700 text-gray-300 border-gray-600 hover:bg-gray-600'
                }`}
              >
                {ZONE_LABELS[zone]}
              </button>
            ))}
          </div>
        </section>

        {/* Drop Zone */}
        <section
          onDrop={handleDrop}
          onDragOver={handleDragOver}
          onDragLeave={handleDragLeave}
          onClick={() => fileInputRef.current?.click()}
          className={`border-2 border-dashed rounded-xl p-12 text-center cursor-pointer transition-colors ${
            isDragging
              ? 'border-kirobi-500 bg-kirobi-500/10'
              : 'border-gray-600 hover:border-kirobi-500/50 hover:bg-gray-800/50'
          }`}
        >
          <CloudArrowUpIcon className="w-12 h-12 mx-auto mb-4 text-gray-400" />
          <p className="text-lg font-medium text-gray-300">
            Dateien hier ablegen oder klicken
          </p>
          <p className="text-sm text-gray-500 mt-1">
            PDF, Bilder, Dokumente — Zone: {ZONE_LABELS[selectedZone]}
          </p>
          <input
            ref={fileInputRef}
            type="file"
            multiple
            onChange={handleInputChange}
            className="hidden"
            accept="image/*,application/pdf,.doc,.docx,.txt,.md"
          />
        </section>

        {/* Upload Progress */}
        {uploads.length > 0 && (
          <section className="bg-gray-800 rounded-xl p-6 border border-gray-700">
            <div className="flex items-center justify-between mb-4">
              <h2 className="text-lg font-semibold">Uploads</h2>
              <button
                onClick={clearDoneUploads}
                className="text-xs text-gray-400 hover:text-white transition-colors"
              >
                Erledigte ausblenden
              </button>
            </div>
            <div className="space-y-3">
              {uploads.map((upload, idx) => (
                <div key={idx} className="space-y-1">
                  <div className="flex items-center justify-between text-sm">
                    <span className="truncate text-gray-300 max-w-[70%]">{upload.filename}</span>
                    <span
                      className={
                        upload.status === 'done'
                          ? 'text-green-400'
                          : upload.status === 'error'
                          ? 'text-red-400'
                          : 'text-gray-400'
                      }
                    >
                      {upload.status === 'done'
                        ? '✓ Fertig'
                        : upload.status === 'error'
                        ? '✗ Fehler'
                        : `${upload.progress}%`}
                    </span>
                  </div>
                  {upload.status === 'error' && upload.error && (
                    <p className="text-xs text-red-400">{upload.error}</p>
                  )}
                  {upload.status === 'uploading' && (
                    <div className="w-full bg-gray-700 rounded-full h-1.5">
                      <div
                        className="bg-kirobi-500 h-1.5 rounded-full transition-all duration-300"
                        style={{ width: `${upload.progress}%` }}
                      />
                    </div>
                  )}
                </div>
              ))}
            </div>
          </section>
        )}

        {/* File List */}
        <section className="bg-gray-800 rounded-xl p-6 border border-gray-700">
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-lg font-semibold">Hochgeladene Dateien</h2>
            <button
              onClick={loadFiles}
              className="text-xs text-gray-400 hover:text-white transition-colors"
            >
              Aktualisieren
            </button>
          </div>

          {loadingFiles ? (
            <p className="text-gray-400 text-sm">Laden...</p>
          ) : files.length === 0 ? (
            <div className="text-center py-8 text-gray-500">
              <DocumentIcon className="w-10 h-10 mx-auto mb-2 opacity-40" />
              <p className="text-sm">Noch keine Dateien hochgeladen</p>
            </div>
          ) : (
            <div className="space-y-2">
              {files.map((file) => (
                <div
                  key={file.id}
                  className="flex items-center space-x-4 p-3 bg-gray-700/50 rounded-lg hover:bg-gray-700 transition-colors"
                >
                  <FileTypeIcon mimeType={file.mime_type} />
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-medium truncate">{file.original_filename}</p>
                    <div className="flex items-center space-x-2 mt-0.5">
                      <span className="text-xs text-gray-400">{formatBytes(file.file_size)}</span>
                      <span className="text-gray-600">·</span>
                      <span
                        className={`text-xs px-1.5 py-0.5 rounded border ${
                          ZONE_COLORS[file.zone] ?? 'bg-gray-600 text-gray-300 border-gray-500'
                        }`}
                      >
                        {ZONE_LABELS[file.zone] ?? file.zone}
                      </span>
                      <span className="text-gray-600">·</span>
                      <span className="text-xs text-gray-400">
                        {new Date(file.created_at).toLocaleDateString('de-DE')}
                      </span>
                    </div>
                  </div>
                  <div className="flex items-center space-x-1 flex-shrink-0">
                    <a
                      href={`/api/uploads/${file.id}/download`}
                      className="p-1.5 text-gray-400 hover:text-white transition-colors"
                      title="Herunterladen"
                    >
                      <ArrowDownTrayIcon className="w-4 h-4" />
                    </a>
                  </div>
                </div>
              ))}
            </div>
          )}
        </section>
      </main>
    </div>
  );
}

// apps/web-svelte/src/routes/upload/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { page } from '$app/stores';
  import { goto } from '$app/navigation';
  import { CloudUpload, FileText, Image, File as FileIcon, Trash2 } from 'lucide-svelte';

  type Zone = 'PUBLIC' | 'WORKSPACE' | 'FAMILY_PRIVATE';

  interface UploadedFile {
    id: string;
    filename: string;
    original_filename: string;
    file_size: number;
    mime_type: string;
    zone: Zone;
    processed?: boolean;
    created_at: string;
  }

  const ZONE_LABELS: Record<Zone, string> = {
    PUBLIC: '🌍 Public',
    WORKSPACE: '💼 Workspace',
    FAMILY_PRIVATE: '👨‍👩‍👦 Family Private',
  };

  const ZONE_COLORS: Record<Zone, string> = {
    PUBLIC: 'bg-green-500/20 text-green-400 border-green-500/30',
    WORKSPACE: 'bg-blue-500/20 text-blue-400 border-blue-500/30',
    FAMILY_PRIVATE: 'bg-purple-500/20 text-purple-400 border-purple-500/30',
  };

  let selectedZone = $state<Zone>(($page.url.searchParams.get('zone') as Zone) ?? 'WORKSPACE');
  let files = $state<UploadedFile[]>([]);
  let uploading = $state(false);
  let dragOver = $state(false);
  let textMode = $state($page.url.searchParams.get('mode') === 'text');
  let textContent = $state('');
  let textTitle = $state('');

  function token() {
    return typeof localStorage !== 'undefined' ? (localStorage.getItem('access_token') ?? '') : '';
  }

  function formatBytes(bytes: number): string {
    if (bytes < 1024) return `${bytes} B`;
    if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
    return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
  }

  async function loadFiles() {
    try {
      const res = await fetch('/api/uploads', {
        headers: { Authorization: `Bearer ${token()}` },
      });
      if (res.status === 401) { goto('/login'); return; }
      files = await res.json();
    } catch (e) { console.error(e); }
  }

  async function uploadFile(file: File) {
    uploading = true;
    const fd = new FormData();
    fd.append('file', file);
    fd.append('zone', selectedZone);
    if (selectedZone === 'FAMILY_PRIVATE') {
      const note = window.prompt('FAMILY_PRIVATE-Upload bleibt lokal. Kurze Freigabe-Notiz:',
        'Bewusst lokal für FAMILY_PRIVATE-Suche freigegeben');
      if (!note?.trim()) { uploading = false; return; }
      fd.append('human_approved', 'true');
      fd.append('approval_note', note.trim());
    }
    try {
      await fetch('/api/upload', {
        method: 'POST',
        headers: { Authorization: `Bearer ${token()}` },
        body: fd,
      });
      await loadFiles();
    } catch (e) { console.error(e); alert('Upload fehlgeschlagen'); }
    finally { uploading = false; }
  }

  async function uploadText() {
    if (!textContent.trim()) return;
    uploading = true;
    try {
      await fetch('/api/upload/text', {
        method: 'POST',
        headers: { Authorization: `Bearer ${token()}`, 'Content-Type': 'application/json' },
        body: JSON.stringify({ content: textContent, title: textTitle || 'Schnellnotiz', zone: selectedZone }),
      });
      textContent = '';
      textTitle = '';
      await loadFiles();
    } catch (e) { console.error(e); alert('Upload fehlgeschlagen'); }
    finally { uploading = false; }
  }

  function handleDrop(e: DragEvent) {
    e.preventDefault();
    dragOver = false;
    const file = e.dataTransfer?.files[0];
    if (file) void uploadFile(file);
  }

  onMount(() => {
    if (!token()) { goto('/login'); return; }
    void loadFiles();
  });
</script>

<div class="min-h-screen bg-gray-950 text-white px-4 py-8 max-w-4xl mx-auto">
  <div class="mb-8">
    <h1 class="text-3xl font-bold">Upload</h1>
    <p class="text-gray-400 mt-1">Dateien und Texte in den lokalen Wissenspfad</p>
  </div>

  <!-- Zone selector -->
  <div class="flex gap-2 mb-6">
    {#each Object.entries(ZONE_LABELS) as [z, label]}
      <button
        onclick={() => selectedZone = z as Zone}
        class="px-3 py-1.5 text-sm rounded-lg border transition {selectedZone === z ? ZONE_COLORS[z as Zone] : 'border-gray-700 bg-gray-900 text-gray-400 hover:border-gray-600'}"
      >{label}</button>
    {/each}
  </div>

  <!-- Mode toggle -->
  <div class="flex gap-2 mb-6">
    <button onclick={() => textMode = false} class="px-4 py-2 rounded-xl text-sm {!textMode ? 'bg-blue-600' : 'bg-gray-800 hover:bg-gray-700'} transition">Datei</button>
    <button onclick={() => textMode = true} class="px-4 py-2 rounded-xl text-sm {textMode ? 'bg-blue-600' : 'bg-gray-800 hover:bg-gray-700'} transition">Schnellnotiz</button>
  </div>

  {#if textMode}
    <div class="rounded-2xl border border-gray-800 bg-gray-900/80 p-5 mb-6">
      <input
        bind:value={textTitle}
        type="text"
        placeholder="Titel (optional)"
        class="w-full mb-3 px-4 py-2 bg-gray-950 border border-gray-700 rounded-xl text-white placeholder-gray-500 focus:outline-none focus:border-blue-500 text-sm"
      />
      <textarea
        bind:value={textContent}
        placeholder="Inhalt hier eingeben…"
        rows="6"
        class="w-full px-4 py-2 bg-gray-950 border border-gray-700 rounded-xl text-white placeholder-gray-500 focus:outline-none focus:border-blue-500 text-sm resize-none"
      ></textarea>
      <button
        onclick={uploadText}
        disabled={uploading || !textContent.trim()}
        class="mt-3 px-6 py-2 bg-blue-600 hover:bg-blue-500 rounded-xl text-sm font-medium transition disabled:opacity-50"
      >{uploading ? 'Speichert…' : 'Speichern'}</button>
    </div>
  {:else}
    <!-- Drop zone -->
    <div
      role="button"
      tabindex="0"
      ondragover={(e) => { e.preventDefault(); dragOver = true; }}
      ondragleave={() => dragOver = false}
      ondrop={handleDrop}
      onclick={() => document.getElementById('file-input')?.click()}
      onkeydown={(e) => e.key === 'Enter' && document.getElementById('file-input')?.click()}
      class="rounded-2xl border-2 border-dashed {dragOver ? 'border-blue-400 bg-blue-500/10' : 'border-gray-700 bg-gray-900/40 hover:border-gray-600'} p-12 text-center cursor-pointer transition mb-6"
    >
      <CloudUpload class="w-10 h-10 text-gray-500 mx-auto mb-3" />
      <p class="text-gray-300 font-medium">Datei hier ablegen oder klicken</p>
      <p class="text-sm text-gray-500 mt-1">PDF, Bild, Text, Dokument</p>
      {#if uploading}<p class="text-blue-400 text-sm mt-2">Wird hochgeladen…</p>{/if}
    </div>
    <input
      id="file-input"
      type="file"
      class="hidden"
      onchange={(e) => { const f = (e.target as HTMLInputElement).files?.[0]; if (f) void uploadFile(f); }}
    />
  {/if}

  <!-- Files list -->
  {#if files.length > 0}
    <h2 class="text-lg font-semibold mb-3">Vorhandene Uploads ({files.length})</h2>
    <div class="space-y-2">
      {#each files as f}
        <div class="flex items-center gap-3 rounded-xl border border-gray-800 bg-gray-900/80 p-3">
          {#if f.mime_type?.startsWith('image/')}
            <Image class="w-6 h-6 text-blue-400 shrink-0" />
          {:else if f.mime_type === 'application/pdf'}
            <FileText class="w-6 h-6 text-red-400 shrink-0" />
          {:else}
            <FileIcon class="w-6 h-6 text-gray-400 shrink-0" />
          {/if}
          <div class="flex-1 min-w-0">
            <p class="text-sm font-medium truncate">{f.original_filename}</p>
            <p class="text-xs text-gray-500">{formatBytes(f.file_size)} · {new Date(f.created_at).toLocaleDateString('de-DE')}</p>
          </div>
          <span class="text-xs border rounded-full px-2 py-0.5 shrink-0 {ZONE_COLORS[f.zone]}">{ZONE_LABELS[f.zone]}</span>
        </div>
      {/each}
    </div>
  {/if}
</div>
