// apps/web-svelte/src/routes/knowledge-base/+page.svelte
<script lang="ts">
  import { Database, Search, Upload, ArrowUpRight, RefreshCw } from 'lucide-svelte';
  import { base } from '$app/paths';

  let { data }: { data: any } = $props();
  const token = $derived(data.session);

  let query = $state('');
  let zone = $state<'ALL'|'PUBLIC'|'WORKSPACE'|'FAMILY_PRIVATE'>('ALL');
  let results = $state<any[]>([]);
  let files = $state<any[]>([]);
  let searching = $state(false);
  let loadingFiles = $state(false);
  let error = $state('');

  const h = () => ({ Authorization: `Bearer ${token}` });

  async function search() {
    if (!query.trim()) return;
    searching = true; error = '';
    try {
      const params = new URLSearchParams({ q: query, limit: '10' });
      if (zone !== 'ALL') params.set('zone', zone);
      const r = await fetch(`/api/retrieval/search?${params}`, { headers: h() });
      const d = await r.json();
      if (!r.ok) throw new Error(d.detail || 'Fehler');
      results = d.results ?? d;
    } catch (e: any) { error = e.message; }
    finally { searching = false; }
  }

  async function loadFiles() {
    loadingFiles = true;
    try {
      const r = await fetch('/api/files?limit=20', { headers: h() });
      if (r.ok) files = (await r.json()).items ?? [];
    } catch {} finally { loadingFiles = false; }
  }

  $effect(() => { loadFiles(); });

  function formatSize(b: number) {
    if (b < 1024) return `${b} B`;
    if (b < 1024*1024) return `${(b/1024).toFixed(1)} KB`;
    return `${(b/1024/1024).toFixed(1)} MB`;
  }
</script>

<svelte:head><title>Knowledge Base · Kirobi</title></svelte:head>

<div class="px-4 py-6 sm:px-6 max-w-7xl mx-auto space-y-6">
  <section class="rounded-3xl border border-cyan-500/20 bg-gradient-to-br from-cyan-900/20 via-gray-900 to-gray-950 p-6">
    <span class="inline-flex items-center gap-2 rounded-full border border-cyan-400/20 bg-cyan-400/10 px-3 py-1 text-xs uppercase tracking-widest text-cyan-200">
      <Database class="h-4 w-4" /> Knowledge Base
    </span>
    <h1 class="mt-4 text-3xl font-bold text-white">Wissens-Datenbank</h1>
    <p class="mt-2 text-sm text-gray-400">RAG-Suche über alle hochgeladenen Dokumente und Embedding-Räume.</p>
  </section>

  <!-- Search -->
  <div class="rounded-3xl border border-white/10 bg-gray-950/70 p-5 space-y-3">
    <div class="flex gap-2">
      <div class="relative flex-1">
        <Search class="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-gray-500" />
        <input bind:value={query} onkeydown={e => e.key === 'Enter' && search()} placeholder="Semantische Suche..."
          class="w-full rounded-2xl border border-white/10 bg-black/30 pl-10 pr-4 py-3 text-sm text-white placeholder-gray-500 focus:outline-none focus:border-cyan-500/50" />
      </div>
      <select bind:value={zone} class="rounded-2xl border border-white/10 bg-black/30 px-3 py-2 text-sm text-white">
        {#each ['ALL','PUBLIC','WORKSPACE','FAMILY_PRIVATE'] as z}<option value={z}>{z}</option>{/each}
      </select>
      <button onclick={search} disabled={!query.trim() || searching}
        class="flex items-center gap-2 rounded-2xl bg-cyan-600 px-5 py-2 text-sm font-medium text-white hover:bg-cyan-500 disabled:opacity-50 transition-colors">
        {#if searching}<RefreshCw class="h-4 w-4 animate-spin" />{:else}<Search class="h-4 w-4" />{/if}
        Suchen
      </button>
    </div>

    {#if error}<div class="rounded-2xl border border-red-500/30 bg-red-500/10 p-3 text-red-300 text-sm">{error}</div>{/if}

    {#if results.length > 0}
      <div class="space-y-2">
        {#each results as r}
          <div class="rounded-2xl border border-white/10 bg-black/20 p-4">
            <div class="flex items-center justify-between mb-2">
              <span class="text-xs font-mono text-cyan-300">{r.source ?? r.id}</span>
              <div class="flex gap-2">
                <span class="inline-flex rounded-full border border-white/15 px-2 py-0.5 text-[10px] text-gray-400">{r.zone}</span>
                <span class="inline-flex rounded-full border border-emerald-400/30 bg-emerald-500/10 px-2 py-0.5 text-[10px] text-emerald-300">{(r.score * 100).toFixed(0)}%</span>
              </div>
            </div>
            <p class="text-sm text-gray-300 leading-relaxed">{r.snippet}</p>
          </div>
        {/each}
      </div>
    {/if}
  </div>

  <!-- Files -->
  <div class="rounded-3xl border border-white/10 bg-gray-950/70 p-5">
    <div class="flex items-center justify-between mb-4">
      <h2 class="text-sm font-semibold text-white">Hochgeladene Dokumente</h2>
      <a href="{base}/upload" class="inline-flex items-center gap-2 rounded-xl border border-white/10 px-3 py-1.5 text-xs text-gray-300 hover:text-white transition-colors">
        <Upload class="h-3.5 w-3.5" /> Upload
      </a>
    </div>
    {#if loadingFiles}
      <p class="text-gray-500 text-sm">Lade...</p>
    {:else if files.length === 0}
      <p class="text-gray-500 text-sm text-center py-4">Keine Dokumente vorhanden.</p>
    {:else}
      <div class="space-y-2">
        {#each files as f}
          <div class="flex items-center justify-between rounded-2xl border border-white/10 bg-black/20 px-4 py-2.5">
            <div>
              <p class="text-sm text-white">{f.original_filename ?? f.filename}</p>
              <p class="text-xs text-gray-500">{f.zone} · {formatSize(f.file_size)}</p>
            </div>
            <span class="text-xs text-gray-600">{new Date(f.created_at).toLocaleDateString('de-DE')}</span>
          </div>
        {/each}
      </div>
    {/if}
  </div>
</div>

// apps/web/src/app/knowledge-base/page.tsx
'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import axios from 'axios';
import {
  CircleStackIcon,
  MagnifyingGlassIcon,
  SparklesIcon,
  ArrowUpRightIcon,
  CloudArrowUpIcon,
} from '@heroicons/react/24/outline';

interface UploadedFile {
  id: string;
  original_filename: string;
  zone: string;
  file_size: number;
  created_at: string;
  metadata?: {
    ingest_status?: string;
    preview?: string;
    char_count?: number;
  };
}

interface SearchResult {
  id: string;
  title?: string;
  zone: string;
  snippet: string;
  score: number;
}

interface SearchResponse {
  results: SearchResult[];
}

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

export default function KnowledgeBasePage() {
  const router = useRouter();
  const [files, setFiles] = useState<UploadedFile[]>([]);
  const [query, setQuery] = useState('');
  const [results, setResults] = useState<SearchResult[]>([]);
  const [searching, setSearching] = useState(false);

  const api = axios.create({
    baseURL: '/api',
    headers: {
      Authorization: `Bearer ${typeof window !== 'undefined' ? localStorage.getItem('access_token') ?? '' : ''}`,
    },
  });

  useEffect(() => {
    const token = localStorage.getItem('access_token');
    if (!token) {
      router.push('/');
      return;
    }
    void api.get<UploadedFile[]>('/uploads').then((response) => setFiles(response.data ?? []));
  }, [router]);

  const zoneCounts = useMemo(() => {
    return files.reduce<Record<string, number>>((acc, file) => {
      acc[file.zone] = (acc[file.zone] ?? 0) + 1;
      return acc;
    }, {});
  }, [files]);

  const runSearch = async () => {
    if (!query.trim()) return;
    setSearching(true);
    try {
      const response = await api.post<SearchResponse>('/rag/search', { query: query.trim() });
      setResults(response.data.results ?? []);
    } finally {
      setSearching(false);
    }
  };

  return (
    <div className="min-h-[calc(100vh-80px)] px-4 py-6 sm:px-6">
      <div className="mx-auto flex max-w-7xl flex-col gap-6">
        <section className="rounded-[2rem] border border-white/10 bg-gradient-to-br from-slate-900/90 via-gray-900 to-slate-950 p-6 shadow-2xl shadow-sky-950/30">
          <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
            <div>
              <span className="inline-flex items-center gap-2 rounded-full border border-sky-400/20 bg-sky-400/10 px-3 py-1 text-xs uppercase tracking-[0.24em] text-sky-200">
                <CircleStackIcon className="h-4 w-4" />
                Knowledge Base
              </span>
              <h1 className="mt-4 text-3xl font-bold tracking-tight text-white">Deine Wissensdatenbank auf einen Blick.</h1>
              <p className="mt-3 max-w-3xl text-sm leading-6 text-gray-400">
                Uploads, Suchzugriff und Graph-Einstieg laufen hier zusammen. Du siehst sofort, wie viel Wissen lokal im System steckt und springst direkt in den passenden Flow.
              </p>
            </div>
            <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
              {['PUBLIC', 'WORKSPACE', 'FAMILY_PRIVATE'].map((zone) => (
                <div key={zone} className="rounded-2xl border border-white/10 bg-black/20 px-4 py-3">
                  <p className="text-xs uppercase tracking-[0.2em] text-gray-500">{zone}</p>
                  <p className="mt-2 text-2xl font-semibold text-white">{zoneCounts[zone] ?? 0}</p>
                </div>
              ))}
              <div className="rounded-2xl border border-white/10 bg-black/20 px-4 py-3">
                <p className="text-xs uppercase tracking-[0.2em] text-gray-500">Total</p>
                <p className="mt-2 text-2xl font-semibold text-white">{files.length}</p>
              </div>
            </div>
          </div>
        </section>

        <section className="grid gap-6 xl:grid-cols-[1.1fr_0.9fr]">
          <div className="rounded-[2rem] border border-white/10 bg-gray-950/70 p-5">
            <div className="flex items-center gap-3">
              <MagnifyingGlassIcon className="h-5 w-5 text-kirobi-300" />
              <h2 className="text-xl font-semibold text-white">Live-Suche</h2>
            </div>
            <div className="mt-4 flex gap-3">
              <input
                type="text"
                value={query}
                onChange={(event) => setQuery(event.target.value)}
                onKeyDown={(event) => {
                  if (event.key === 'Enter') void runSearch();
                }}
                placeholder="Wissen durchsuchen ..."
                className="flex-1 rounded-2xl border border-white/10 bg-gray-900 px-4 py-3 text-white outline-none ring-0 placeholder:text-gray-500"
              />
              <button
                type="button"
                onClick={() => void runSearch()}
                className="rounded-2xl bg-kirobi-600 px-5 py-3 text-sm font-semibold text-white transition hover:bg-kirobi-500"
              >
                {searching ? 'Suche…' : 'Suchen'}
              </button>
            </div>
            <div className="mt-5 space-y-3">
              {results.map((result) => (
                <div key={result.id} className="rounded-2xl border border-white/10 bg-white/[0.03] p-4">
                  <div className="flex items-center justify-between gap-3">
                    <p className="text-sm font-semibold text-white">{result.title ?? result.id}</p>
                    <span className="rounded-full border border-white/10 px-2 py-0.5 text-xs text-gray-400">{result.zone}</span>
                  </div>
                  <p className="mt-2 text-sm text-gray-400">{result.snippet}</p>
                </div>
              ))}
              {!searching && results.length === 0 && (
                <div className="rounded-2xl border border-dashed border-white/10 bg-white/[0.02] p-4 text-sm text-gray-500">
                  Noch keine Live-Suche gestartet. Nutze alternativ die volle Suchoberfläche.
                </div>
              )}
            </div>
          </div>

          <div className="space-y-6">
            <section className="rounded-[2rem] border border-white/10 bg-gray-950/70 p-5">
              <div className="flex items-center gap-3">
                <CloudArrowUpIcon className="h-5 w-5 text-emerald-300" />
                <h2 className="text-xl font-semibold text-white">Letzte Wissenseinträge</h2>
              </div>
              <div className="mt-4 space-y-3">
                {files.slice(0, 6).map((file) => (
                  <div key={file.id} className="rounded-2xl border border-white/10 bg-white/[0.03] p-4">
                    <div className="flex items-center justify-between gap-3">
                      <p className="text-sm font-semibold text-white">{file.original_filename}</p>
                      <span className="rounded-full border border-white/10 px-2 py-0.5 text-xs text-gray-400">{file.zone}</span>
                    </div>
                    <p className="mt-2 text-xs text-gray-500">{formatBytes(file.file_size)} · {new Date(file.created_at).toLocaleString('de-DE')}</p>
                    {file.metadata?.preview && <p className="mt-2 text-sm text-gray-400">{file.metadata.preview}</p>}
                  </div>
                ))}
              </div>
            </section>

            <section className="grid gap-3 sm:grid-cols-2">
              <Link href="/upload" className="rounded-[2rem] border border-white/10 bg-gray-950/70 p-5 transition hover:border-kirobi-500/30">
                <p className="text-sm font-semibold text-white">Mehr Wissen einspeisen</p>
                <p className="mt-2 text-sm text-gray-400">Upload, Schnellnotiz und lokale Ingest-Pfade öffnen.</p>
                <ArrowUpRightIcon className="mt-4 h-5 w-5 text-kirobi-300" />
              </Link>
              <Link href="/knowledge-graph" className="rounded-[2rem] border border-white/10 bg-gray-950/70 p-5 transition hover:border-kirobi-500/30">
                <p className="text-sm font-semibold text-white">Knowledge Graph</p>
                <p className="mt-2 text-sm text-gray-400">Visueller Einstieg in die aktuelle Wissenslandschaft.</p>
                <SparklesIcon className="mt-4 h-5 w-5 text-violet-300" />
              </Link>
            </section>
          </div>
        </section>
      </div>
    </div>
  );
}
