// apps/web-svelte/src/routes/chat/+page.svelte
<script lang="ts">
  import type { PageData } from './$types';
  import { base } from '$app/paths';
  import { MessageCircle, Plus, LogOut, Mic, StopCircle, Paperclip, Send, Settings2, ChevronRight } from 'lucide-svelte';

  let { data }: { data: PageData } = $props();

  interface Message {
    id: string;
    role: 'user' | 'assistant' | 'system';
    content: string;
    created_at: string;
    model_used?: string | null;
    metadata?: {
      agent?: string;
      reasoning_mode?: string;
      reasoning_label?: string;
      visible_reasoning_summary?: string[];
      source_trace?: string[];
    } | null;
  }

  interface Conversation {
    id: string;
    title: string | null;
    zone: string;
    created_at: string;
    updated_at: string;
  }

  type Zone = 'PUBLIC' | 'WORKSPACE' | 'FAMILY_PRIVATE';

  const ZONE_LABELS: Record<Zone, string> = {
    PUBLIC: '🌍 Public',
    WORKSPACE: '💼 Workspace',
    FAMILY_PRIVATE: '👨‍👩‍👦 Family',
  };

  const ZONE_COLORS: Record<Zone, string> = {
    PUBLIC: 'bg-green-500/20 text-green-300 border-green-500/30',
    WORKSPACE: 'bg-blue-500/20 text-blue-300 border-blue-500/30',
    FAMILY_PRIVATE: 'bg-purple-500/20 text-purple-300 border-purple-500/30',
  };

  let conversations = $state<Conversation[]>([]);
  let activeConversation = $state<Conversation | null>(null);
  let messages = $state<Message[]>([]);
  let input = $state('');
  let loading = $state(false);
  let sidebarOpen = $state(false);
  let selectedZone = $state<Zone>('FAMILY_PRIVATE');
  let availableZones = $state<Zone[]>(['WORKSPACE', 'FAMILY_PRIVATE', 'PUBLIC']);
  let runtimeOptions = $state({ available_models: [] as string[], default_model: 'llama3.1:8b', agent_options: [] as {id:string,label:string}[], reasoning_modes: [] as {id:string,label:string}[], source_modes: [] as {id:string,label:string}[], voice: { available: false } });
  let selectedModel = $state('');
  let selectedAgent = $state('kirobi');
  let reasoningMode = $state('normal');
  let sourceModes = $state<string[]>(['local']);
  let showReasoning = $state(true);
  let settingsOpen = $state(false);
  let recording = $state(false);
  let transcribing = $state(false);
  let messagesEnd: HTMLDivElement | undefined = $state();

  let mediaRecorder: MediaRecorder | null = null;
  let mediaStream: MediaStream | null = null;
  let audioChunks: Blob[] = [];

  const token = $derived(data.session);

  async function apiFetch(path: string, options: RequestInit = {}) {
    const res = await fetch(`/api${path}`, {
      ...options,
      headers: { 'Authorization': `Bearer ${token}`, 'Content-Type': 'application/json', ...(options.headers ?? {}) },
    });
    if (!res.ok) throw new Error(`API ${res.status}`);
    return res.json();
  }

  async function init() {
    try {
      const [perms, convs, rt] = await Promise.all([
        apiFetch('/auth/me/permissions'),
        apiFetch('/conversations'),
        apiFetch('/chat/runtime/options'),
      ]);
      const writable = (perms.zones ?? []).filter((z: {zone: string, can_write: boolean}) => z.can_write && ZONE_LABELS[z.zone as Zone]).map((z: {zone: Zone}) => z.zone as Zone);
      if (writable.length > 0) availableZones = writable;
      conversations = convs;
      runtimeOptions = rt;
      selectedModel = rt.default_model || '';
      if (convs.length > 0) await selectConversation(convs[0]);
    } catch (e) { console.error(e); }
  }

  async function selectConversation(conv: Conversation) {
    activeConversation = conv;
    sidebarOpen = false;
    try {
      messages = await apiFetch(`/conversations/${conv.id}/messages`);
      setTimeout(() => messagesEnd?.scrollIntoView({ behavior: 'smooth' }), 50);
    } catch (e) { console.error(e); }
  }

  async function createNew() {
    try {
      const conv = await apiFetch('/conversations', {
        method: 'POST',
        body: JSON.stringify({ title: `${ZONE_LABELS[selectedZone]} Gespräch`, zone: selectedZone }),
      });
      conversations = [conv, ...conversations];
      activeConversation = conv;
      messages = [];
      sidebarOpen = false;
    } catch (e) { console.error(e); }
  }

  async function sendMessage(e: Event) {
    e.preventDefault();
    if (!input.trim() || !activeConversation || loading) return;
    const content = input;
    input = '';
    loading = true;
    messages = [...messages, { id: 'tmp-' + Date.now(), role: 'user', content, created_at: new Date().toISOString() }];
    setTimeout(() => messagesEnd?.scrollIntoView({ behavior: 'smooth' }), 50);
    try {
      await apiFetch(`/conversations/${activeConversation.id}/messages`, {
        method: 'POST',
        body: JSON.stringify({ content, model: selectedModel || undefined, agent: selectedAgent, reasoning_mode: reasoningMode, source_modes: sourceModes, show_reasoning: showReasoning }),
      });
      messages = await apiFetch(`/conversations/${activeConversation.id}/messages`);
    } catch (e) { console.error(e); }
    finally { loading = false; setTimeout(() => messagesEnd?.scrollIntoView({ behavior: 'smooth' }), 100); }
  }

  async function toggleVoice() {
    if (recording && mediaRecorder) {
      mediaRecorder.stop();
      recording = false;
      return;
    }
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
      mediaStream = stream;
      audioChunks = [];
      const mr = new MediaRecorder(stream);
      mediaRecorder = mr;
      mr.ondataavailable = (e) => { if (e.data.size > 0) audioChunks.push(e.data); };
      mr.onstop = async () => {
        transcribing = true;
        try {
          const blob = new Blob(audioChunks, { type: mr.mimeType || 'audio/webm' });
          const fd = new FormData();
          fd.append('audio_file', blob, 'voice.webm');
          fd.append('language', 'de');
          const res = await fetch('/voice/stt/transcribe', { method: 'POST', headers: { 'Authorization': `Bearer ${token}` }, body: fd });
          if (res.ok) {
            const p = await res.json();
            const t = p.text || p.transcription || '';
            if (t) input = input ? `${input} ${t}` : t;
          }
        } finally {
          mediaStream?.getTracks().forEach(t => t.stop());
          mediaStream = null; audioChunks = []; transcribing = false; recording = false;
        }
      };
      mr.start();
      recording = true;
    } catch { alert('Mikrofonzugriff nicht verfügbar'); }
  }

  $effect(() => { init(); });
  $effect(() => { return () => { mediaStream?.getTracks().forEach(t => t.stop()); }; });
</script>

<svelte:head><title>Chat · Kirobi</title></svelte:head>

<div class="flex h-[calc(100vh-3.5rem)] md:h-[calc(100vh-3.5rem)] bg-gray-950 text-white overflow-hidden">
  <!-- Sidebar -->
  <div class="
    {sidebarOpen ? 'translate-x-0' : '-translate-x-full'} md:translate-x-0
    fixed md:static inset-y-0 left-0 z-50 w-64
    bg-gray-900 border-r border-white/10
    transition-transform duration-300 flex flex-col
  ">
    <div class="p-4 border-b border-white/10 space-y-3">
      <p class="font-semibold text-sm">{data.user?.display_name ?? 'Kirobi'}</p>
      <button onclick={createNew} class="w-full flex items-center justify-center gap-2 px-3 py-2 bg-aurora-cyan/15 hover:bg-aurora-cyan/25 text-aurora-cyan rounded-lg text-sm transition-colors">
        <Plus class="w-4 h-4" /> Neues Gespräch
      </button>
      <div class="flex flex-wrap gap-1.5">
        {#each availableZones as zone}
          <button onclick={() => selectedZone = zone} class="rounded-full border px-2 py-0.5 text-xs transition-colors {selectedZone === zone ? ZONE_COLORS[zone] : 'border-white/10 text-gray-400'}">
            {ZONE_LABELS[zone]}
          </button>
        {/each}
      </div>
    </div>
    <div class="flex-1 overflow-y-auto p-2">
      {#each conversations as conv}
        <button onclick={() => selectConversation(conv)} class="w-full text-left px-3 py-2 rounded-lg mb-1 transition-colors {activeConversation?.id === conv.id ? 'bg-aurora-cyan/15 text-aurora-cyan' : 'hover:bg-white/5 text-gray-300'}">
          <div class="flex items-center gap-2">
            <MessageCircle class="w-4 h-4 flex-shrink-0" />
            <span class="truncate text-sm">{conv.title || 'Gespräch'}</span>
          </div>
          <p class="text-xs text-gray-500 mt-0.5">{new Date(conv.updated_at).toLocaleDateString('de-DE')} · {conv.zone}</p>
        </button>
      {/each}
    </div>
    <div class="p-4 border-t border-white/10">
      <a href="{base}/login" class="w-full flex items-center justify-center gap-2 px-3 py-2 bg-red-600/20 hover:bg-red-600/30 text-red-300 rounded-lg text-sm transition-colors">
        <LogOut class="w-4 h-4" /> Abmelden
      </a>
    </div>
  </div>

  <!-- Chat area -->
  <div class="flex-1 flex flex-col min-w-0">
    <!-- Header -->
    <div class="border-b border-white/10 bg-gray-900/50 px-4 py-2 flex items-center gap-2">
      <button onclick={() => sidebarOpen = !sidebarOpen} class="md:hidden text-gray-400 hover:text-white p-1">
        <MessageCircle class="w-5 h-5" />
      </button>
      {#if activeConversation}
        <span class="rounded-full border px-2 py-0.5 text-xs {ZONE_COLORS[activeConversation.zone as Zone] ?? 'border-white/10 text-gray-300'}">
          {ZONE_LABELS[activeConversation.zone as Zone] ?? activeConversation.zone}
        </span>
        <span class="text-xs text-gray-400">{selectedModel || runtimeOptions.default_model}</span>
        <span class="text-xs text-gray-500">{runtimeOptions.agent_options.find(a => a.id === selectedAgent)?.label ?? selectedAgent}</span>
      {/if}
      <button onclick={() => settingsOpen = !settingsOpen} class="ml-auto flex items-center gap-1 px-2 py-1 rounded-lg border text-xs transition-colors {settingsOpen ? 'border-aurora-cyan/40 text-aurora-cyan' : 'border-white/10 text-gray-400 hover:text-white'}">
        <Settings2 class="w-3.5 h-3.5" />
      </button>
    </div>

    {#if settingsOpen}
      <div class="border-b border-white/10 bg-gray-900 px-4 py-3 grid grid-cols-2 md:grid-cols-4 gap-3">
        <label class="space-y-1">
          <span class="text-[10px] uppercase tracking-wider text-gray-500">Agent</span>
          <select bind:value={selectedAgent} class="w-full rounded-lg border border-white/10 bg-gray-950 px-2 py-1.5 text-xs text-white">
            {#each runtimeOptions.agent_options as a}<option value={a.id}>{a.label}</option>{/each}
          </select>
        </label>
        <label class="space-y-1">
          <span class="text-[10px] uppercase tracking-wider text-gray-500">Modell</span>
          <select bind:value={selectedModel} class="w-full rounded-lg border border-white/10 bg-gray-950 px-2 py-1.5 text-xs text-white">
            {#each (runtimeOptions.available_models.length > 0 ? runtimeOptions.available_models : [runtimeOptions.default_model]) as m}<option value={m}>{m}</option>{/each}
          </select>
        </label>
        <div class="space-y-1">
          <span class="text-[10px] uppercase tracking-wider text-gray-500">Denkgrad</span>
          <div class="flex flex-wrap gap-1">
            {#each runtimeOptions.reasoning_modes as mode}
              <button onclick={() => reasoningMode = mode.id} class="px-2 py-1 rounded border text-[10px] transition-colors {reasoningMode === mode.id ? 'border-aurora-violet/60 bg-aurora-violet/15 text-aurora-violet' : 'border-white/10 text-gray-400'}">{mode.label}</button>
            {/each}
          </div>
        </div>
        <label class="flex items-center gap-2 text-xs text-gray-300">
          <input type="checkbox" bind:checked={showReasoning} class="rounded border-white/20" />
          Reasoning anzeigen
        </label>
      </div>
    {/if}

    <!-- Messages -->
    <div class="flex-1 overflow-y-auto p-4 space-y-3">
      {#if !activeConversation}
        <div class="h-full flex items-center justify-center text-gray-500">
          <div class="text-center">
            <MessageCircle class="w-12 h-12 mx-auto mb-3 opacity-30" />
            <p>Wähle ein Gespräch oder starte ein neues</p>
          </div>
        </div>
      {:else if messages.length === 0}
        <div class="h-full flex items-center justify-center text-gray-500">
          <div class="text-center">
            <p class="text-lg mb-2">Hallo {data.user?.display_name ?? ''}! 👋</p>
            <p class="text-sm">Wie kann ich dir helfen?</p>
          </div>
        </div>
      {:else}
        {#each messages as msg}
          <div class="flex {msg.role === 'user' ? 'justify-end' : 'justify-start'}">
            <div class="max-w-[80%] p-3 rounded-2xl text-sm {msg.role === 'user' ? 'bg-aurora-cyan/20 text-white' : 'bg-white/5 text-gray-100'}">
              <p class="whitespace-pre-wrap">{msg.content}</p>
              {#if msg.role === 'assistant' && msg.metadata?.visible_reasoning_summary?.length && showReasoning}
                <div class="mt-2 pt-2 border-t border-white/10 space-y-1">
                  {#each msg.metadata.visible_reasoning_summary as s}
                    <p class="text-[10px] text-gray-400">• {s}</p>
                  {/each}
                </div>
              {/if}
              <p class="text-[10px] text-gray-500 mt-1.5">{new Date(msg.created_at).toLocaleTimeString('de-DE', { hour: '2-digit', minute: '2-digit' })}</p>
            </div>
          </div>
        {/each}
        {#if loading}
          <div class="flex justify-start">
            <div class="bg-white/5 p-3 rounded-2xl">
              <div class="flex gap-1">
                <div class="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style="animation-delay:0ms"></div>
                <div class="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style="animation-delay:150ms"></div>
                <div class="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style="animation-delay:300ms"></div>
              </div>
            </div>
          </div>
        {/if}
        <div bind:this={messagesEnd}></div>
      {/if}
    </div>

    <!-- Input -->
    {#if activeConversation}
      <div class="border-t border-white/10 p-3">
        <form onsubmit={sendMessage} class="flex items-end gap-2">
          <button type="button" onclick={toggleVoice} disabled={transcribing} class="flex-shrink-0 p-2.5 rounded-xl transition-colors disabled:opacity-50 {recording ? 'bg-red-600 hover:bg-red-700' : 'bg-white/5 hover:bg-white/10'}">
            {#if recording}<StopCircle class="w-5 h-5" />{:else}<Mic class="w-5 h-5" />{/if}
          </button>
          <textarea
            bind:value={input}
            onkeydown={(e) => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); sendMessage(e); } }}
            placeholder={transcribing ? 'Transkribiere...' : 'Schreibe eine Nachricht…'}
            disabled={loading || transcribing}
            rows={1}
            class="flex-1 bg-white/5 border border-white/10 rounded-xl px-3 py-2.5 text-sm text-white resize-none focus:outline-none focus:border-aurora-cyan/40 placeholder-gray-600"
          ></textarea>
          <button type="submit" disabled={loading || !input.trim()} class="flex-shrink-0 p-2.5 bg-aurora-cyan/20 hover:bg-aurora-cyan/30 text-aurora-cyan rounded-xl transition-colors disabled:opacity-30">
            <Send class="w-5 h-5" />
          </button>
        </form>
      </div>
    {/if}
  </div>

  {#if sidebarOpen}
    <button onclick={() => sidebarOpen = false} class="md:hidden fixed inset-0 bg-black/60 z-40" aria-label="Sidebar schließen"></button>
  {/if}
</div>

// apps/web/src/app/chat/page.tsx
'use client';

import { useEffect, useState, useRef } from 'react';
import { useRouter } from 'next/navigation';
import axios from 'axios';
import ReactMarkdown from 'react-markdown';
import {
  PaperAirplaneIcon,
  PhotoIcon,
  ArrowRightOnRectangleIcon,
  PlusCircleIcon,
  ChatBubbleLeftRightIcon,
  UserCircleIcon
} from '@heroicons/react/24/outline';

interface User {
  id: string;
  username: string;
  display_name: string;
  role: string;
}

interface Message {
  id: string;
  role: 'user' | 'assistant' | 'system';
  content: string;
  created_at: string;
}

interface Conversation {
  id: string;
  title: string | null;
  zone: string;
  created_at: string;
  updated_at: string;
}

export default function ChatPage() {
  const router = useRouter();
  const [user, setUser] = useState<User | null>(null);
  const [conversations, setConversations] = useState<Conversation[]>([]);
  const [activeConversation, setActiveConversation] = useState<Conversation | null>(null);
  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(false);
  const [uploading, setUploading] = useState(false);
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const axiosInstance = axios.create({
    baseURL: '/api',
    headers: {
      Authorization: `Bearer ${typeof window !== 'undefined' ? localStorage.getItem('access_token') : ''}`,
    },
  });

  useEffect(() => {
    const token = localStorage.getItem('access_token');
    if (!token) {
      router.push('/');
      return;
    }

    loadUser();
    loadConversations();
  }, []);

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  const loadUser = async () => {
    try {
      const response = await axiosInstance.get('/auth/me');
      setUser(response.data);
    } catch (error) {
      console.error('Failed to load user:', error);
      router.push('/');
    }
  };

  const loadConversations = async () => {
    try {
      const response = await axiosInstance.get('/conversations');
      setConversations(response.data);

      // Load most recent conversation
      if (response.data.length > 0 && !activeConversation) {
        selectConversation(response.data[0]);
      }
    } catch (error) {
      console.error('Failed to load conversations:', error);
    }
  };

  const selectConversation = async (conversation: Conversation) => {
    setActiveConversation(conversation);
    setSidebarOpen(false);

    try {
      const response = await axiosInstance.get(`/conversations/${conversation.id}/messages`);
      setMessages(response.data);
    } catch (error) {
      console.error('Failed to load messages:', error);
    }
  };

  const createNewConversation = async () => {
    try {
      const response = await axiosInstance.post('/conversations', {
        title: 'Neues Gespräch',
        zone: 'FAMILY_PRIVATE',
      });

      const newConv = response.data;
      setConversations([newConv, ...conversations]);
      setActiveConversation(newConv);
      setMessages([]);
      setSidebarOpen(false);
    } catch (error) {
      console.error('Failed to create conversation:', error);
    }
  };

  const sendMessage = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!input.trim() || !activeConversation || loading) return;

    const userMessage = input;
    setInput('');
    setLoading(true);

    // Optimistically add user message
    const tempUserMessage: Message = {
      id: 'temp-' + Date.now(),
      role: 'user',
      content: userMessage,
      created_at: new Date().toISOString(),
    };
    setMessages([...messages, tempUserMessage]);

    try {
      await axiosInstance.post(
        `/conversations/${activeConversation.id}/messages`,
        { content: userMessage }
      );

      // Reload messages to get the full conversation including AI response
      const messagesResponse = await axiosInstance.get(
        `/conversations/${activeConversation.id}/messages`
      );
      setMessages(messagesResponse.data);
    } catch (error) {
      console.error('Failed to send message:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setUploading(true);
    const formData = new FormData();
    formData.append('file', file);
    formData.append('zone', 'FAMILY_PRIVATE');

    try {
      await axiosInstance.post('/upload', formData, {
        headers: {
          'Content-Type': 'multipart/form-data',
        },
      });

      // Add a message about the uploaded file
      if (activeConversation) {
        setInput(`[Datei hochgeladen: ${file.name}]\n\n`);
      }
    } catch (error) {
      console.error('Failed to upload file:', error);
      alert('Datei-Upload fehlgeschlagen');
    } finally {
      setUploading(false);
    }
  };

  const handleLogout = () => {
    localStorage.removeItem('access_token');
    localStorage.removeItem('refresh_token');
    router.push('/');
  };

  if (!user) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-900">
        <div className="text-white">Laden...</div>
      </div>
    );
  }

  return (
    <div className="flex h-screen bg-gray-900 text-white">
      {/* Sidebar */}
      <div className={`${sidebarOpen ? 'translate-x-0' : '-translate-x-full'} md:translate-x-0 fixed md:static inset-y-0 left-0 z-50 w-64 bg-gray-800 border-r border-gray-700 transition-transform duration-300 ease-in-out`}>
        <div className="flex flex-col h-full">
          {/* Header */}
          <div className="p-4 border-b border-gray-700">
            <div className="flex items-center space-x-3 mb-4">
              <UserCircleIcon className="w-10 h-10 text-kirobi-500" />
              <div>
                <p className="font-semibold">{user.display_name}</p>
                <p className="text-xs text-gray-400">@{user.username}</p>
              </div>
            </div>

            <button
              onClick={createNewConversation}
              className="w-full flex items-center justify-center space-x-2 px-4 py-2 bg-kirobi-600 hover:bg-kirobi-700 rounded-lg transition-colors"
            >
              <PlusCircleIcon className="w-5 h-5" />
              <span>Neues Gespräch</span>
            </button>
          </div>

          {/* Conversations List */}
          <div className="flex-1 overflow-y-auto p-2">
            {conversations.map((conv) => (
              <button
                key={conv.id}
                onClick={() => selectConversation(conv)}
                className={`w-full text-left px-3 py-2 rounded-lg mb-1 transition-colors ${
                  activeConversation?.id === conv.id
                    ? 'bg-kirobi-600'
                    : 'hover:bg-gray-700'
                }`}
              >
                <div className="flex items-center space-x-2">
                  <ChatBubbleLeftRightIcon className="w-4 h-4 flex-shrink-0" />
                  <span className="truncate text-sm">
                    {conv.title || 'Neues Gespräch'}
                  </span>
                </div>
                <p className="text-xs text-gray-400 mt-1">
                  {new Date(conv.updated_at).toLocaleDateString('de-DE')}
                </p>
              </button>
            ))}
          </div>

          {/* Logout Button */}
          <div className="p-4 border-t border-gray-700">
            <button
              onClick={handleLogout}
              className="w-full flex items-center justify-center space-x-2 px-4 py-2 bg-red-600 hover:bg-red-700 rounded-lg transition-colors"
            >
              <ArrowRightOnRectangleIcon className="w-5 h-5" />
              <span>Abmelden</span>
            </button>
          </div>
        </div>
      </div>

      {/* Main Chat Area */}
      <div className="flex-1 flex flex-col">
        {/* Mobile Header */}
        <div className="md:hidden bg-gray-800 border-b border-gray-700 p-4 flex items-center justify-between">
          <button
            onClick={() => setSidebarOpen(!sidebarOpen)}
            className="text-gray-400 hover:text-white"
          >
            <ChatBubbleLeftRightIcon className="w-6 h-6" />
          </button>
          <h1 className="font-semibold">Kirobi</h1>
          <div className="w-6" />
        </div>

        {/* Messages */}
        <div className="flex-1 overflow-y-auto p-4 space-y-4">
          {!activeConversation ? (
            <div className="h-full flex items-center justify-center text-gray-400">
              <div className="text-center">
                <ChatBubbleLeftRightIcon className="w-16 h-16 mx-auto mb-4 opacity-50" />
                <p>Wähle ein Gespräch oder starte ein neues</p>
              </div>
            </div>
          ) : messages.length === 0 ? (
            <div className="h-full flex items-center justify-center text-gray-400">
              <div className="text-center">
                <p className="text-lg mb-2">Hallo {user.display_name}! 👋</p>
                <p>Wie kann ich dir heute helfen?</p>
              </div>
            </div>
          ) : (
            messages.map((message) => (
              <div
                key={message.id}
                className={`flex ${message.role === 'user' ? 'justify-end' : 'justify-start'}`}
              >
                <div
                  className={`max-w-[80%] md:max-w-[70%] p-4 rounded-lg ${
                    message.role === 'user'
                      ? 'bg-kirobi-600'
                      : 'bg-gray-700'
                  }`}
                >
                  <ReactMarkdown className="prose prose-invert prose-sm max-w-none">
                    {message.content}
                  </ReactMarkdown>
                  <p className="text-xs text-gray-400 mt-2">
                    {new Date(message.created_at).toLocaleTimeString('de-DE', {
                      hour: '2-digit',
                      minute: '2-digit',
                    })}
                  </p>
                </div>
              </div>
            ))
          )}
          {loading && (
            <div className="flex justify-start">
              <div className="bg-gray-700 p-4 rounded-lg">
                <div className="flex space-x-2">
                  <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style={{ animationDelay: '0ms' }}></div>
                  <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style={{ animationDelay: '150ms' }}></div>
                  <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style={{ animationDelay: '300ms' }}></div>
                </div>
              </div>
            </div>
          )}
          <div ref={messagesEndRef} />
        </div>

        {/* Input */}
        {activeConversation && (
          <div className="border-t border-gray-700 p-4">
            <form onSubmit={sendMessage} className="flex items-end space-x-2">
              <input
                type="file"
                ref={fileInputRef}
                onChange={handleFileUpload}
                accept="image/*,application/pdf,.doc,.docx"
                className="hidden"
              />

              <button
                type="button"
                onClick={() => fileInputRef.current?.click()}
                disabled={uploading}
                className="flex-shrink-0 p-3 bg-gray-700 hover:bg-gray-600 rounded-lg transition-colors disabled:opacity-50"
              >
                <PhotoIcon className="w-5 h-5" />
              </button>

              <textarea
                value={input}
                onChange={(e) => setInput(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === 'Enter' && !e.shiftKey) {
                    e.preventDefault();
                    sendMessage(e);
                  }
                }}
                placeholder="Schreibe eine Nachricht..."
                className="flex-1 bg-gray-700 text-white rounded-lg px-4 py-3 focus:outline-none focus:ring-2 focus:ring-kirobi-500 resize-none"
                rows={1}
                disabled={loading}
              />

              <button
                type="submit"
                disabled={loading || !input.trim()}
                className="flex-shrink-0 p-3 bg-kirobi-600 hover:bg-kirobi-700 rounded-lg transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
              >
                <PaperAirplaneIcon className="w-5 h-5" />
              </button>
            </form>

            <p className="text-xs text-gray-500 mt-2 text-center">
              🔒 Deine Daten bleiben privat und lokal
            </p>
          </div>
        )}
      </div>

      {/* Sidebar Overlay (Mobile) */}
      {sidebarOpen && (
        <div
          className="md:hidden fixed inset-0 bg-black bg-opacity-50 z-40"
          onClick={() => setSidebarOpen(false)}
        />
      )}
    </div>
  );
}
