// apps/web/src/app/workbench/page.tsx
'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import {
  ArrowTopRightOnSquareIcon,
  CheckCircleIcon,
  CommandLineIcon,
  ExclamationTriangleIcon,
  RectangleGroupIcon,
  XCircleIcon,
} from '@heroicons/react/24/outline';
import { RUNTIME_PROBES, RUNTIME_SURFACES } from '@/lib/runtime-surfaces';
import { useClientSearchParams } from '@/lib/use-client-search-params';

type ProbeStatus = 'online' | 'offline' | 'unknown';

interface ProbeResult {
  status: ProbeStatus;
  detail: string;
}

export default function WorkbenchPage() {
  const router = useRouter();
  const searchParams = useClientSearchParams();
  const [selectedSurfaceId, setSelectedSurfaceId] = useState('open-webui');
  const [probes, setProbes] = useState<Record<string, ProbeResult>>({});

  useEffect(() => {
    const token = localStorage.getItem('access_token');
    if (!token) {
      router.push('/');
      return;
    }
    const requested = searchParams.get('surface');
    if (requested && RUNTIME_SURFACES.some((surface) => surface.id === requested && surface.kind === 'workbench')) {
      setSelectedSurfaceId(requested);
    }
  }, [router, searchParams]);

  useEffect(() => {
    void Promise.all(
      RUNTIME_PROBES.map(async (probe) => {
        try {
          const response = await fetch(probe.path, { cache: 'no-store' });
          return [probe.id, { status: response.ok ? 'online' : 'offline', detail: `HTTP ${response.status}` }] as const;
        } catch (error: unknown) {
          return [probe.id, { status: 'offline', detail: error instanceof Error ? error.message : 'unreachable' }] as const;
        }
      })
    ).then((entries) => setProbes(Object.fromEntries(entries)));
  }, []);

  const workbenchSurfaces = useMemo(
    () => RUNTIME_SURFACES.filter((surface) => surface.kind === 'workbench'),
    []
  );

  const selectedSurface =
    workbenchSurfaces.find((surface) => surface.id === selectedSurfaceId) ?? workbenchSurfaces[0];
  const embeddedPath = `${selectedSurface.directPath}${selectedSurface.directPath.includes('?') ? '&' : '?'}embed=1`;
  const embeddingBlocked = selectedSurface.id === 'qdrant';

  const statusTone = (status: ProbeStatus) => {
    if (status === 'online') return 'border-emerald-500/30 bg-emerald-500/10 text-emerald-100';
    if (status === 'offline') return 'border-red-500/30 bg-red-500/10 text-red-100';
    return 'border-amber-500/30 bg-amber-500/10 text-amber-100';
  };

  const statusIcon = (status: ProbeStatus) => {
    if (status === 'online') return <CheckCircleIcon className="h-4 w-4 text-emerald-400" />;
    if (status === 'offline') return <XCircleIcon className="h-4 w-4 text-red-400" />;
    return <ExclamationTriangleIcon className="h-4 w-4 text-amber-400" />;
  };

  return (
    <div className="min-h-screen bg-gray-950 text-white">
      <main className="mx-auto flex max-w-7xl flex-col gap-6 px-4 pb-24 pt-6 md:px-6">
        <section className="rounded-3xl border border-gray-800 bg-gradient-to-br from-gray-900 via-gray-900 to-gray-950 p-6">
          <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
            <div className="space-y-3">
              <span className="inline-flex w-fit items-center gap-2 rounded-full border border-gray-700 bg-gray-900 px-3 py-1 text-xs font-medium text-gray-200">
                <RectangleGroupIcon className="h-4 w-4 text-kirobi-300" />
                Embedded Workbench
              </span>
              <div>
                <h1 className="text-3xl font-bold tracking-tight">Service-UIs direkt im Control Plane.</h1>
                <p className="mt-2 max-w-2xl text-sm leading-6 text-gray-400">
                  Statt Kontextwechseln springst du zwischen Open WebUI, Flowise und Qdrant
                  innerhalb der OpenDisruption-Shell. Wenn ein Service Framing blockiert,
                  bleibt der Direktlink als Fallback sichtbar.
                </p>
              </div>
            </div>
            <div className="flex flex-wrap gap-3">
              <Link
                href="/control-center"
                className="inline-flex items-center gap-2 rounded-xl border border-gray-700 bg-gray-900 px-4 py-2.5 text-sm font-medium text-gray-100 transition hover:border-kirobi-500/40"
              >
                <CommandLineIcon className="h-4 w-4" />
                Zum Control Center
              </Link>
              <a
                href={selectedSurface.directPath}
                target="_blank"
                rel="noreferrer"
                className="inline-flex items-center gap-2 rounded-xl bg-kirobi-600 px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-kirobi-500"
              >
                <ArrowTopRightOnSquareIcon className="h-4 w-4" />
                Direkt öffnen
              </a>
            </div>
          </div>
        </section>

        <section className="grid gap-6 xl:grid-cols-[300px_1fr]">
          <aside className="space-y-4">
            <div className="rounded-3xl border border-gray-800 bg-gray-900/80 p-4">
              <h2 className="text-lg font-semibold">Workbench-Flächen</h2>
              <div className="mt-4 space-y-2">
                {workbenchSurfaces.map((surface) => (
                  <button
                    key={surface.id}
                    type="button"
                    onClick={() => setSelectedSurfaceId(surface.id)}
                    className={`w-full rounded-2xl border p-4 text-left transition ${
                      selectedSurface.id === surface.id
                        ? 'border-kirobi-500/40 bg-kirobi-500/10'
                        : 'border-gray-800 bg-gray-950/60 hover:border-gray-700'
                    }`}
                  >
                    <span className="inline-flex rounded-full border border-gray-700 bg-gray-900 px-2 py-0.5 text-[11px] uppercase tracking-wide text-gray-300">
                      {surface.badge}
                    </span>
                    <p className="mt-3 text-sm font-semibold text-white">{surface.label}</p>
                    <p className="mt-2 text-sm text-gray-400">{surface.summary}</p>
                    <p className="mt-3 text-xs text-gray-500">{surface.guard}</p>
                  </button>
                ))}
              </div>
            </div>

            <div className="rounded-3xl border border-gray-800 bg-gray-900/80 p-4">
              <h2 className="text-lg font-semibold">Runtime</h2>
              <div className="mt-4 space-y-2">
                {RUNTIME_PROBES.map((probe) => {
                  const result = probes[probe.id] ?? { status: 'unknown' as ProbeStatus, detail: 'wird geprüft' };
                  return (
                    <div key={probe.id} className={`rounded-2xl border px-3 py-2 text-sm ${statusTone(result.status)}`}>
                      <div className="flex items-center gap-2">
                        {statusIcon(result.status)}
                        <span className="font-medium capitalize">{probe.id}</span>
                      </div>
                      <p className="mt-1 text-xs opacity-80">{result.detail}</p>
                    </div>
                  );
                })}
              </div>
            </div>
          </aside>

          <section className="space-y-4">
            <div className="rounded-3xl border border-gray-800 bg-gray-900/80 p-5">
              <div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between">
                <div>
                  <p className="text-xs uppercase tracking-[0.24em] text-gray-500">{selectedSurface.badge}</p>
                  <h2 className="mt-2 text-2xl font-semibold">{selectedSurface.label}</h2>
                  <p className="mt-2 max-w-3xl text-sm leading-6 text-gray-400">{selectedSurface.summary}</p>
                </div>
                <div className="rounded-2xl border border-gray-800 bg-gray-950/60 px-4 py-3 text-sm text-gray-400">
                  <p className="font-medium text-white">Guard</p>
                  <p className="mt-1">{selectedSurface.guard}</p>
                </div>
              </div>
            </div>

            <div className="overflow-hidden rounded-3xl border border-gray-800 bg-gray-900/80">
              <div className="flex items-center justify-between border-b border-gray-800 px-4 py-3">
                <div>
                  <p className="text-sm font-semibold text-white">Embedded view</p>
                  <p className="text-xs text-gray-500">{embeddedPath}</p>
                </div>
                <a
                  href={selectedSurface.directPath}
                  target="_blank"
                  rel="noreferrer"
                  className="inline-flex items-center gap-2 rounded-lg border border-gray-700 bg-gray-950 px-3 py-2 text-sm text-gray-200 transition hover:border-kirobi-500/40"
                >
                  <ArrowTopRightOnSquareIcon className="h-4 w-4" />
                  Neuer Tab
                </a>
              </div>
              <div className="h-[68vh] min-h-[540px] bg-black">
                {embeddingBlocked ? (
                  <div className="flex h-full items-center justify-center p-8">
                    <div className="max-w-md rounded-3xl border border-amber-500/30 bg-amber-500/10 p-6 text-center text-amber-100">
                      <p className="text-lg font-semibold">Direktstart erforderlich</p>
                      <p className="mt-3 text-sm leading-6">
                        Qdrant blockiert Einbettung per Sicherheitsheader. Öffne die Oberfläche direkt im neuen Tab über den Button oben.
                      </p>
                    </div>
                  </div>
                ) : (
                  <iframe
                    key={selectedSurface.id}
                    src={embeddedPath}
                    title={selectedSurface.label}
                    className="h-full w-full"
                  />
                )}
              </div>
            </div>
          </section>
        </section>
      </main>
    </div>
  );
}

// apps/web-svelte/src/routes/workbench/+page.svelte
<script lang="ts">
  import { CheckCircle, XCircle, AlertTriangle, ExternalLink, ArrowUpRight, RefreshCw } from 'lucide-svelte';
  import { page } from '$app/stores';

  let { data }: { data: any } = $props();
  const token = $derived(data.session);

  type ProbeStatus = 'online' | 'offline' | 'unknown';
  interface ProbeResult { status: ProbeStatus; detail: string; }

  const SURFACES = [
    { id: 'knowledge-base', label: 'Knowledge Base', path: '/knowledge-base', directPath: '/knowledge-base', summary: 'Uploads, Wissenssuche, Graph-Einstieg', badge: 'Native', embeddable: false },
    { id: 'chat', label: 'Chat', path: '/chat', directPath: '/chat', summary: 'Direkter Einstieg in lokale Gespräche', badge: 'Native', embeddable: false },
    { id: 'open-webui', label: 'Open WebUI', path: '?surface=open-webui', directPath: '/open-webui/', summary: 'LLM-Workbench für tiefe Modellinteraktion', badge: 'Workbench', embeddable: true },
    { id: 'flowise', label: 'Flowise', path: '?surface=flowise', directPath: '/flowise/', summary: 'Visuelle Flow- und Agent-Orchestrierung', badge: 'Workbench', embeddable: true },
    { id: 'qdrant', label: 'Qdrant', path: '?surface=qdrant', directPath: '/qdrant/dashboard/', summary: 'Vektor-DB-Diagnostik und Collection-Checks', badge: 'Workbench', embeddable: false },
  ];

  const PROBES = [
    { id: 'api', path: '/api/health' },
    { id: 'auth', path: '/api/auth/health' },
    { id: 'telegram', path: '/telegram/health' },
    { id: 'voice', path: '/voice/health' },
  ];

  let probes = $state<Record<string, ProbeResult>>({});
  let probingDone = $state(false);

  let activeSurface = $derived($page.url.searchParams.get('surface') ?? '');
  let surfaceConfig = $derived(SURFACES.find(s => s.id === activeSurface));

  async function runProbes() {
    const results = await Promise.all(PROBES.map(async p => {
      try {
        const r = await fetch(p.path, { cache: 'no-store' });
        return [p.id, { status: r.ok ? 'online' : 'offline', detail: `HTTP ${r.status}` }];
      } catch { return [p.id, { status: 'offline', detail: 'unreachable' }]; }
    }));
    probes = Object.fromEntries(results);
    probingDone = true;
  }

  const BADGE_COLOR: Record<string, string> = {
    Native: 'bg-emerald-500/10 border-emerald-400/30 text-emerald-200',
    Workbench: 'bg-blue-500/10 border-blue-400/30 text-blue-200',
    Ops: 'bg-amber-500/10 border-amber-400/30 text-amber-200',
  };

  $effect(() => { runProbes(); });
</script>

<svelte:head><title>Workbench · Kirobi</title></svelte:head>

<div class="px-4 py-4 sm:px-6 sm:py-6 max-w-7xl mx-auto space-y-4 sm:space-y-6 pb-20 md:pb-0">
  {#if !activeSurface}
    <!-- Overview -->
    <div class="flex items-center justify-between gap-3">
      <h1 class="text-2xl font-bold text-white">Workbench</h1>
      <button onclick={runProbes} class="p-2 rounded-xl border border-white/10 hover:bg-white/5 transition-colors min-h-[44px] min-w-[44px] flex items-center justify-center">
        <RefreshCw class="h-4 w-4 {!probingDone ? 'animate-spin' : ''}" />
      </button>
    </div>

    <!-- Probes -->
    <section class="rounded-3xl border border-white/10 bg-gray-950/70 p-4 sm:p-5">
      <h2 class="text-sm font-semibold text-white mb-4">Runtime Health</h2>
      <div class="grid grid-cols-2 gap-2">
        {#each PROBES as probe}
          {@const r = probes[probe.id]}
          <div class="flex items-center gap-2 rounded-2xl border px-3 py-3
            {!r ? 'border-white/10 bg-white/[0.02]' : r.status === 'online' ? 'border-emerald-500/30 bg-emerald-500/10' : 'border-red-500/30 bg-red-500/10'}">
            {#if !r}
              <div class="h-3 w-3 rounded-full bg-gray-600 animate-pulse flex-shrink-0"></div>
            {:else if r.status === 'online'}
              <CheckCircle class="h-3.5 w-3.5 text-emerald-400 flex-shrink-0" />
            {:else}
              <XCircle class="h-3.5 w-3.5 text-red-400 flex-shrink-0" />
            {/if}
            <span class="text-xs font-medium text-white">{probe.id}</span>
          </div>
        {/each}
      </div>
    </section>

    <!-- Surfaces Grid -->
    <section class="grid gap-4 grid-cols-1 sm:grid-cols-2">
      {#each SURFACES as surface}
        <div class="rounded-2xl border border-white/10 bg-gray-950/70 p-4 space-y-3">
          <div class="flex items-start justify-between gap-2">
            <div class="min-w-0">
              <span class="inline-flex text-[10px] border rounded-full px-2 py-0.5 {BADGE_COLOR[surface.badge] ?? BADGE_COLOR.Native}">{surface.badge}</span>
              <p class="mt-2 font-semibold text-white">{surface.label}</p>
              <p class="mt-1 text-xs text-gray-500">{surface.summary}</p>
            </div>
          </div>
          <div class="flex gap-2">
            {#if surface.embeddable}
              <a href={surface.path} class="flex-1 flex items-center justify-center gap-1.5 rounded-xl bg-white/[0.05] border border-white/10 py-2.5 text-xs text-white hover:bg-white/10 transition-colors min-h-[44px]">
                Einbetten <ArrowUpRight class="h-3 w-3" />
              </a>
            {/if}
            <a href={surface.directPath} target="_blank" class="flex-1 flex items-center justify-center gap-1.5 rounded-xl bg-white/[0.05] border border-white/10 py-2.5 text-xs text-white hover:bg-white/10 transition-colors min-h-[44px]">
              Öffnen <ExternalLink class="h-3 w-3" />
            </a>
          </div>
        </div>
      {/each}
    </section>

  {:else if surfaceConfig?.embeddable}
    <!-- Embedded View -->
    <div class="flex items-center justify-between gap-2 flex-wrap">
      <h1 class="text-xl font-bold text-white">{surfaceConfig.label}</h1>
      <div class="flex gap-2">
        <a href={surfaceConfig.directPath} target="_blank" class="flex items-center gap-2 text-sm text-gray-400 hover:text-white min-h-[44px] px-2">
          <ExternalLink class="h-4 w-4" /> Neues Tab
        </a>
        <a href="/workbench" class="text-sm text-gray-500 hover:text-white min-h-[44px] flex items-center px-2">← Zurück</a>
      </div>
    </div>
    <iframe src={surfaceConfig.directPath} class="w-full rounded-2xl border border-white/10" style="height: calc(100dvh - 160px);" title={surfaceConfig.label}></iframe>
  {:else if activeSurface}
    <div class="rounded-3xl border border-amber-500/20 bg-amber-500/10 p-6 text-center space-y-4">
      <AlertTriangle class="h-8 w-8 text-amber-400 mx-auto" />
      <p class="text-sm text-amber-200">Dieser Service kann nicht eingebettet werden.</p>
      {#if surfaceConfig}
        <a href={surfaceConfig.directPath} target="_blank" class="inline-flex items-center gap-2 rounded-xl bg-amber-600 px-5 py-3 text-sm text-white hover:bg-amber-500 min-h-[44px]">
          <ExternalLink class="h-4 w-4" /> In neuem Tab öffnen
        </a>
      {/if}
      <a href="/workbench" class="block text-sm text-gray-500 hover:text-white mt-2">← Zurück</a>
    </div>
  {/if}
</div>
